# Perhitungan Sentralitas

## Import Library

In [ ]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [33]:
# Pengaturan tampilan
pd.set_option('display.max_colwidth', None)

# Membaca CSV
df = pd.read_csv('../data/processed/edge.csv')

# Konversi numerik
df['Weight'] = pd.to_numeric(df['Weight'])
df['Inverse_Weight'] = pd.to_numeric(df['Inverse_Weight'])

# Konversi Guru_Id dan Murid_Id ke integer (jika kolom ada)
for col in ['Edge_id', 'Guru_Id', 'Murid_Id']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Pembulatan
df['Inverse_Weight'] = df['Inverse_Weight'].round(8)

# Urutkan berdasarkan Weight terbesar
df = df.sort_values(by='Weight', ascending=False).reset_index(drop=True)

print(f"Total baris: {len(df):,}")
print(f"Kolom: {list(df.columns)}")
print(f"Tipe data:\n{df.dtypes}")

# Tampilkan 10 baris — format 8 desimal hanya pada Inverse_Weight
with pd.option_context('display.float_format', '{:.8f}'.format):
    display(df.head(10))

Total baris: 776,798
Kolom: ['Edge_id', 'Guru_Id', 'Guru', 'Nama_Guru', 'Murid_Id', 'Murid', 'Nama_Murid', 'Weight', 'Inverse_Weight']
Tipe data:
Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
5,6,1,ابو هريره,Abu Hurairah,34,ابو سلمه,Abu Salamah,4502,0.00022212
6,7,7,الزهري,Az-Zuhri,18,معمر,Ma'mar,4381,0.00022826
7,8,1,ابو هريره,Abu Hurairah,50,ابو صالح,Abu Shalih,3972,0.00025176
8,9,3,عائشه,Aisyah,57,عروه,Urwah,3953,0.00025297
9,10,3,عائشه,Aisyah,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,3950,0.00025316

## Load Data

In [34]:
print(df.dtypes)

Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

In [35]:
df.shape

(776798, 9)

In [36]:
# df["Inverse_Weight"] = df["Weight"].apply(lambda x: 1/x if x > 0 else 0)

In [37]:
df['Weight'] = pd.to_numeric(df['Weight'])
df['Inverse_Weight'] = pd.to_numeric(df['Inverse_Weight'])
print(df.dtypes)

Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

In [38]:
display(df)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
...,...,...,...,...,...,...,...,...,...
776793,776794,7379,كيسان,Kysan,2764,محمد بن ربيعه,Muhammad bin Rby'h,1,1.00000000
776794,776795,115,عليا,'lya,11903,صفوان بن عيسي الزهري,Shafwan bin Isa Az-Zuhri,1,1.00000000
776795,776796,70179,ناسا من الصحابه,Nasa Mn Al-Shhabh,448,جابر بن زيد,Jabir bin Zaid,1,1.00000000
776796,776797,7,الزهري,Az-Zuhri,2927,عبد الرزاق بن همام,Abdurrazzaq bin Hmam,1,1.00000000
776797,776798,3232,لانس بن مالك,Lans bin Malik,3109,العلاء بن زياد,Al-'la' bin Zyad,1,1.00000000

### Bentuk graph

In [39]:
G = nx.from_pandas_edgelist(
    df,
    source='Murid',
    target='Guru',
    edge_attr=['Weight', 'Inverse_Weight'],
    create_using=nx.DiGraph()
)

In [40]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 177047
Jumlah edge : 776798

In [41]:
display(df)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
...,...,...,...,...,...,...,...,...,...
776793,776794,7379,كيسان,Kysan,2764,محمد بن ربيعه,Muhammad bin Rby'h,1,1.00000000
776794,776795,115,عليا,'lya,11903,صفوان بن عيسي الزهري,Shafwan bin Isa Az-Zuhri,1,1.00000000
776795,776796,70179,ناسا من الصحابه,Nasa Mn Al-Shhabh,448,جابر بن زيد,Jabir bin Zaid,1,1.00000000
776796,776797,7,الزهري,Az-Zuhri,2927,عبد الرزاق بن همام,Abdurrazzaq bin Hmam,1,1.00000000
776797,776798,3232,لانس بن مالك,Lans bin Malik,3109,العلاء بن زياد,Al-'la' bin Zyad,1,1.00000000

In [42]:
# Hapus self-loop
G.remove_edges_from(nx.selfloop_edges(G))

In [43]:
print("Jumlah node setelah hapus self-loop:", G.number_of_nodes())
print("Jumlah edge setelah hapus self-loop:", G.number_of_edges())

Jumlah node setelah hapus self-loop: 177047
Jumlah edge setelah hapus self-loop: 776798

In [44]:
# Degree
degree_dict = dict(G.degree(weight='Weight'))
print("✅ Degree selesai")

# Degree Centrality
deg = nx.degree_centrality(G)
print("✅ Degree Centrality selesai.")

# In-Degree Centrality
if G.is_directed():
    in_deg = nx.in_degree_centrality(G)
    print("✅ In-Degree Centrality selesai.")
else:
    in_deg = {}

# Out-Degree Centrality
if G.is_directed():
    out_deg = nx.out_degree_centrality(G)
    print("✅ Out-Degree Centrality selesai.")
else:
    out_deg = {}

✅ Degree selesai
✅ Degree Centrality selesai.
✅ In-Degree Centrality selesai.
✅ Out-Degree Centrality selesai.

In [45]:
# === Eigenvector Centrality (Power Iteration)
try:
    eigenvector_centrality = nx.eigenvector_centrality(G, max_iter=5000, tol=1e-05, weight='Weight')
    print("✅ Eigenvector Centrality selesai.")
except nx.PowerIterationFailedConvergence:
    eigenvector_centrality = {}

# # === Eigenvector Centrality (NumPy version)
# try:
#     eigenvector_numpy_centrality = nx.eigenvector_centrality_numpy(G, weight='Weight')
#     print("✅ Eigenvector Numpy Centrality selesai.")
# except Exception as e:
#     eigenvector_numpy_centrality = {}
#     print(f"Proses gagal: {e}")

✅ Eigenvector Centrality selesai.

In [46]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 177047
Jumlah edge : 776798

In [47]:
print(f"Total edges dalam dataset lengkap: {len(df)}")
print(f"Unique Murid: {df['Murid'].nunique()}")
print(f"Unique Guru: {df['Guru'].nunique()}")
print(f"Total unique Perawi: {len(set(df['Murid'].unique()) | set(df['Guru'].unique()))}")
display(df.head(20))

Total edges dalam dataset lengkap: 776798
Unique Murid: 168903
Unique Guru: 153468
Total unique Perawi: 177047

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
5,6,1,ابو هريره,Abu Hurairah,34,ابو سلمه,Abu Salamah,4502,0.00022212
6,7,7,الزهري,Az-Zuhri,18,معمر,Ma'mar,4381,0.00022826
7,8,1,ابو هريره,Abu Hurairah,50,ابو صالح,Abu Shalih,3972,0.00025176
8,9,3,عائشه,Aisyah,57,عروه,Urwah,3953,0.00025297
9,10,3,عائشه,Aisyah,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,3950,0.00025316
10,11,20,جابر,Jabir,42,ابو الزبير,Abu Az-Zubair,3690,0.00027100
11,12,12,انس,Anas,10,قتاده,Qatadah,3284,0.00030451
12,13,1,ابو هريره,Abu Hurairah,102,الاعرج,Al-A'raj,3065,0.00032626
13,14,5,شعبه,Syu'bah,73,محمد بن جعفر,Muhammad bin Ja'far,3047,0.00032819
14,15,12,انس,Anas,70,ثابت,Tsabit,2751,0.00036350
15,16,8,الاعمش,Al-A'masy,56,ابو معاويه,Abu Mu'awiyah,2737,0.00036536
16,17,10,قتاده,Qatadah,5,شعبه,Syu'bah,2690,0.00037175
17,18,38,ابو العباس محمد بن يعقوب,Abul Abbas Muhammad bin Ya'qub,14,ابو عبد الله الحافظ,Abu Abdullah Al-Hafizh,2487,0.00040209
18,19,162,ابو عبد الله بن احمد بن حنبل,Abu Abdullah bin Ahmad bin Hanbal,77,عبد الله بن احمد بن حنبل,Abdullah bin Ahmad bin Hanbal,2476,0.00040388
19,20,50,ابو صالح,Abu Shalih,8,الاعمش,Al-A'masy,2417,0.00041374

In [ ]:
# ==============================================
# Kombinasi Semua Centrality Measures
# ==============================================
import pandas as pd

# Build mapping nama Arab → Perawi_ID dari edge.csv (konsisten dengan Edges.ipynb)
guru_map  = df[['Guru', 'Guru_Id']].drop_duplicates().rename(columns={'Guru': 'Nama', 'Guru_Id': 'Perawi_ID'})
murid_map = df[['Murid', 'Murid_Id']].drop_duplicates().rename(columns={'Murid': 'Nama', 'Murid_Id': 'Perawi_ID'})
perawi_id_map = (
    pd.concat([guru_map, murid_map])
    .drop_duplicates('Nama')
    .set_index('Nama')['Perawi_ID']
    .to_dict()
)

# Semua nodes dari graph
all_nodes = list(G.nodes())

centrality_results = pd.DataFrame({
    'Perawi_ID'             : pd.array([perawi_id_map.get(n) for n in all_nodes], dtype='Int64'),
    'Perawi'                : all_nodes,
    'Degree'                : [degree_dict.get(n, 0) for n in all_nodes],
    'Degree_Centrality'     : [deg.get(n, 0) for n in all_nodes],
    'In_Degree_Centrality'  : [in_deg.get(n, 0) for n in all_nodes],
    'Out_Degree_Centrality' : [out_deg.get(n, 0) for n in all_nodes],
    'Eigenvector_Centrality': [eigenvector_centrality.get(n, 0) for n in all_nodes],
    # 'Closeness_Centrality'  : [closeness.get(n, 0) for n in all_nodes],
    # 'Betweenness_Centrality': [bet_node.get(n, 0) for n in all_nodes],
})

centrality_results = centrality_results.round(8)
centrality_results = centrality_results.sort_values('Degree_Centrality', ascending=False).reset_index(drop=True)

print(f"Total Perawi di graph : {G.number_of_nodes()}")
print(f"Total baris dataframe : {len(centrality_results)}")
print(f"NaN Perawi_ID         : {centrality_results['Perawi_ID'].isna().sum()}")
print(f"Nodes dengan Degree > 0: {(centrality_results['Degree'] > 0).sum()}")
print(f"\n{'='*80}")
display(centrality_results)

Total Perawi di graph : 177047
Total baris dataframe : 177047
NaN Perawi_ID         : 1
Nodes dengan Degree > 0: 177047

================================================================================

,Perawi_ID,Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality
0,1,ابو هريره,52846,0.02722456,0.01992702,0.00729754,0.51953871
1,6,سفيان,48556,0.02645075,0.01295144,0.01349932,0.04942856
2,5,شعبه,50261,0.02440044,0.01198559,0.01241485,0.05623588
3,2,ابن عباس,39321,0.02039018,0.01504129,0.00534889,0.26587741
4,3,عائشه,32693,0.01731189,0.01317172,0.00414017,0.48360279
...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,1,0.00000565,0.00000000,0.00000565,0.00000000
177043,177285,جد بن فضيل,1,0.00000565,0.00000565,0.00000000,0.00000000
177044,177279,عمرو بن قره,1,0.00000565,0.00000000,0.00000565,0.00000000
177045,177276,يعلي بن سياه,1,0.00000565,0.00000565,0.00000000,0.00000057
177046,177271,عباد بن عمرو السلمي,1,0.00000565,0.00000565,0.00000000,0.00000000

In [50]:
df_subset = df.head(50000)
display(df_subset)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
...,...,...,...,...,...,...,...,...,...
49995,49996,214,مسلم بن ابراهيم,Muslim bin Ibrahim,289,ابو اميه,Abu Amyh,6,0.16666667
49996,49997,78,قتيبه بن سعيد,Qtybh bin Sa'id,1692,ابو داود السجزي,Abu Dawud Al-Sjzy,6,0.16666667
49997,49998,252,الحارث,Al-Harts,532,مغيره,Mghyrh,6,0.16666667
49998,49999,15,علي,Ali,6390,عبد الله بن صفوان,Abdullah bin Shafwan,6,0.16666667
49999,50000,91,سليمان بن احمد,Sulaiman bin Ahmad,447,عبد الله بن محمد بن جعفر,Abdullah bin Muhammad bin Ja'far,6,0.16666667

In [51]:
# Buat graph dari subset
G = nx.from_pandas_edgelist(
    df_subset,
    source='Murid',
    target='Guru',
    edge_attr=['Weight', 'Inverse_Weight'],
    create_using=nx.DiGraph()
)

print("✅ Graph berhasil dibuat dari subset.")

✅ Graph berhasil dibuat dari subset.

In [52]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 14695
Jumlah edge : 50000

In [ ]:
from tqdm import tqdm
import pandas as pd

# ==========================================
# Hitung Closeness Centrality
# ==========================================

raw_closeness = {}

nodes = list(G.nodes())

for node in tqdm(nodes, desc="Closeness Centrality"):
    raw_closeness[node] = nx.closeness_centrality(
        G,
        u=node,
        distance="Inverse_Weight"
    )

print("✅ Closeness Centrality selesai.")

# ==========================================
# Normalisasi Min-Max (0 - 1)
# ==========================================

min_val = min(raw_closeness.values())
max_val = max(raw_closeness.values())

normalized_closeness = {
    node: (
        (value - min_val) / (max_val - min_val)
        if max_val > min_val else 1.0
    )
    for node, value in raw_closeness.items()
}

print("✅ Normalisasi selesai.")
display(normalized_closeness)

Closeness Centrality:   1%|          | 146/14695 [01:17<2:11:19,  1.85it/s]

In [ ]:
import networkx as nx
from tqdm import tqdm

def betweenness_centrality_with_progress(G, normalized=True, weight=None):
    nodes = list(G.nodes())
    bet = dict.fromkeys(nodes, 0.0)

    for s in tqdm(nodes, desc="Betweenness Centrality (Nodes)"):
        # hitung betweenness subset: dari source s ke semua node
        contrib = nx.betweenness_centrality_subset(
            G, sources=[s], targets=nodes,
            normalized=normalized, weight=weight
        )
        # gabungkan kontribusi
        for n, v in contrib.items():
            bet[n] += v

    return bet


# =====================
# Pemakaian
# =====================
bet_node = betweenness_centrality_with_progress(G, normalized=True, weight="Inverse_weight")

print("✅ Betweenness selesai.")

Betweenness Centrality (Nodes): 100%|██████████| 14695/14695 [24:18<00:00, 10.08it/s]

✅ Betweenness selesai.

In [55]:
# ==============================================
# Kombinasi Semua Centrality Measures
# ==============================================
import pandas as pd

# Buat mapping Arab → Indonesia dari Guru_ID dan Murid_ID di df
guru_map  = df[['Guru', 'Guru_ID']].drop_duplicates().rename(columns={'Guru': 'Perawi', 'Guru_ID': 'Nama'})
murid_map = df[['Murid', 'Murid_ID']].drop_duplicates().rename(columns={'Murid': 'Perawi', 'Murid_ID': 'Nama'})
name_map  = (pd.concat([guru_map, murid_map])
               .drop_duplicates('Perawi')
               .set_index('Perawi')['Nama']
               .to_dict())

# Semua nodes dari degree_dict (177047 total perawi)
all_nodes = list(degree_dict.keys())

centrality_results = pd.DataFrame({
    'Perawi'                : all_nodes,
    'Nama_Perawi'           : [name_map.get(n, '') for n in all_nodes],
    'Degree'                : [degree_dict.get(n, 0) for n in all_nodes],
    'In_Degree'             : [in_deg.get(n, 0) for n in all_nodes],
    'Out_Degree'            : [out_deg.get(n, 0) for n in all_nodes],
    'Degree_Centrality'     : [degree_dict.get(n, 0) / (len(all_nodes) - 1) if len(all_nodes) > 1 else 0 for n in all_nodes],
    'Eigenvector_Centrality': [eigenvector_centrality.get(n, 0) for n in all_nodes],
    'Closeness_Centrality'  : [normalized_closeness.get(n, 0) for n in all_nodes],
    'Betweenness_Centrality': [bet_node.get(n, 0) for n in all_nodes],
})

centrality_results = centrality_results.round(8)
centrality_results = centrality_results.sort_values('Degree', ascending=False).reset_index(drop=True)

print(f"Total Perawi: {len(centrality_results)}")
print(f"\n{'='*80}")
display(centrality_results.head(20))

KeyError: "['Guru_ID'] not in index"

In [ ]:
display(centrality_results)

,Perawi,Degree,In_Degree,Out_Degree,Degree_Centrality,Eigenvector_Centrality,Closeness_Centrality,Betweenness_Centrality
0,ابو هريره,52846,0.01992702,0.00729754,0.29848740,0.51953871,1.00000000,0.04998978
1,شعبه,50261,0.01198559,0.01241485,0.28388667,0.05623588,0.95371344,0.04446962
2,سفيان,48556,0.01295144,0.01349932,0.27425641,0.04942856,0.94618551,0.03844485
3,الزهري,42075,0.00878303,0.00828598,0.23765010,0.11976357,0.96101995,0.02112129
4,ابن عباس,39321,0.01504129,0.00534889,0.22209482,0.26587741,0.98636409,0.02443526
...,...,...,...,...,...,...,...,...
177042,طلحه بن عبد الله يعني ابن عوف,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000
177043,جد بن فضيل,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000
177044,عمرو بن قره,1,0.00000000,0.00000565,0.00000565,0.00000000,0.00000000,0.00000000
177045,يعلي بن سياه,1,0.00000565,0.00000000,0.00000565,0.00000057,0.00000000,0.00000000
177046,عباد بن عمرو السلمي,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000

## Tambah Kolom Perawi_ID dan Nama_Perawi ke centrality_results

In [53]:
centrality_results.insert(0, 'Perawi_ID', range(1, len(centrality_results) + 1))

print("✅ Selesai!")
display(centrality_results[['Perawi_ID', 'Perawi', 'Nama_Perawi', 'Degree']].head(10))

✅ Selesai!

KeyError: "['Nama_Perawi'] not in index"

In [ ]:
display (df[['Murid', 'Murid_ID', 'Guru', 'Guru_ID']])

,Murid,Murid_ID,Guru,Guru_ID
0,نافع,Nafi',ابن عمر,Ibnu Umar
1,عبد الرزاق,Abdurrazzaq,معمر,Ma'mar
2,هشام بن عروه,Hisyam bin Urwah,ابو هشام بن عروه,Abu Hisyam bin Urwah
3,عكرمه,Ikrimah,ابن عباس,Ibnu Abbas
4,سعيد بن جبير,Sa'id bin Jubair,ابن عباس,Ibnu Abbas
...,...,...,...,...
776793,محمد بن ربيعه,Muhammad bin Rby'h,كيسان,Kysan
776794,صفوان بن عيسي الزهري,Shafwan bin Isa Az-Zuhri,عليا,'lya
776795,جابر بن زيد,Jabir bin Zaid,ناسا من الصحابه,Nasa Mn Al-Shhabh
776796,عبد الرزاق بن همام,Abdurrazzaq bin Hmam,الزهري,Az-Zuhri
776797,العلاء بن زياد,Al-'la' bin Zyad,لانس بن مالك,Lans bin Malik

In [ ]:
display(centrality_results)

,Perawi,Perawi_ID,Degree,In_Degree,Out_Degree,Degree_Centrality,Eigenvector_Centrality,Closeness_Centrality,Betweenness_Centrality
0,ابو هريره,Abu Hurairah,52846,0.01992702,0.00729754,0.29848740,0.51953871,1.00000000,0.04998978
1,شعبه,Syu'bah,50261,0.01198559,0.01241485,0.28388667,0.05623588,0.95371344,0.04446962
2,سفيان,Sufyan,48556,0.01295144,0.01349932,0.27425641,0.04942856,0.94618551,0.03844485
3,الزهري,Az-Zuhri,42075,0.00878303,0.00828598,0.23765010,0.11976357,0.96101995,0.02112129
4,ابن عباس,Ibnu Abbas,39321,0.01504129,0.00534889,0.22209482,0.26587741,0.98636409,0.02443526
...,...,...,...,...,...,...,...,...,...
177042,طلحه بن عبد الله يعني ابن عوف,Thalhah bin Abdullah Y'ny Ibnu 'wf,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000
177043,جد بن فضيل,Jd bin Fdhyl,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000
177044,عمرو بن قره,Amru bin Qrh,1,0.00000000,0.00000565,0.00000565,0.00000000,0.00000000,0.00000000
177045,يعلي بن سياه,Y'ly bin Syah,1,0.00000565,0.00000000,0.00000565,0.00000057,0.00000000,0.00000000
177046,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.00000565,0.00000000,0.00000565,0.00000000,0.00000000,0.00000000

In [ ]:
display(centrality_results[['Perawi_ID', 'Perawi', 'Nama_Perawi']])

In [ ]:
centrality_results.to_csv("../data/processed/centrality.csv", index=False, encoding='utf-8-sig')

In [ ]:
# Format Eigenvector_Centrality tanpa scientific notation
centrality_results['Eigenvector_Centrality'] = (
    centrality_results['Eigenvector_Centrality']
    .apply(lambda x: f"{x:.6f}")
)

# Buat mapping nama Arab → nama Indonesia dari kolom Guru/Nama_Guru dan Murid/Nama_Murid
guru_name_map  = df[['Guru', 'Nama_Guru']].drop_duplicates().set_index('Guru')['Nama_Guru'].to_dict()
murid_name_map = df[['Murid', 'Nama_Murid']].drop_duplicates().set_index('Murid')['Nama_Murid'].to_dict()
nama_map = {**murid_name_map, **guru_name_map}

# Tambah kolom Nama_Perawi setelah kolom Perawi
centrality_results.insert(2, 'Nama_Perawi', centrality_results['Perawi'].map(nama_map))

display(centrality_results)

In [ ]:
# import json

# nodes = centrality_results.to_dict(orient="records")

# with open("node.json", "w", encoding="utf-8") as f:
#     json.dump(nodes, f, ensure_ascii=False, indent=2)

## Simpan ke PostgreSQL

**Prasyarat sebelum menjalankan sel ini:**
1. Install PostgreSQL: https://www.postgresql.org/download/windows/
2. Buka pgAdmin atau psql, buat database baru:
   ```sql
   CREATE DATABASE sanad_db;
   ```
3. Install library Python (jalankan di terminal):
   ```
   pip install psycopg2-binary sqlalchemy
   ```

## Entity Relationship Diagram (ERD)

In [ ]:
from sqlalchemy import create_engine, text

# ── Pilih mode koneksi ───────────────────────────────────────────────────────
MODE = "supabase"  # ganti ke "local" untuk PostgreSQL lokal

if MODE == "supabase":
    # Ambil dari: Supabase Dashboard → Settings → Database → Connection string → URI
    # Ganti [YOUR-PASSWORD] dan [YOUR-PROJECT-REF]
    DB_URL = (
        "postgresql+psycopg2://postgres.[YOUR-PROJECT-REF]:[YOUR-PASSWORD]"
        "@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
        "?sslmode=require"  # wajib untuk Supabase
    )
else:
    DB_URL = "postgresql+psycopg2://postgres:your_password@localhost:5432/sanad_db"

engine = create_engine(DB_URL, echo=False)

# Test koneksi
with engine.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print("✅ Koneksi berhasil:", result.fetchone()[0])

In [ ]:
# ── Buat tabel dengan skema yang tepat ──────────────────────────────────────
schema_sql = """
DROP TABLE IF EXISTS edges   CASCADE;
DROP TABLE IF EXISTS perawi  CASCADE;

CREATE TABLE perawi (
    perawi_id              INTEGER PRIMARY KEY,  -- urutan 1, 2, 3, ...
    perawi                 TEXT NOT NULL,         -- nama Arab
    nama_perawi            TEXT,                  -- nama Indonesia
    degree                 BIGINT,
    in_degree              FLOAT,
    out_degree             FLOAT,
    degree_centrality      FLOAT,
    eigenvector_centrality FLOAT,
    closeness_centrality   FLOAT,
    betweenness_centrality FLOAT
);

CREATE TABLE edges (
    id             SERIAL PRIMARY KEY,
    guru           TEXT NOT NULL,
    murid          TEXT NOT NULL,
    guru_id        TEXT,
    murid_id       TEXT,
    weight         INTEGER,
    inverse_weight FLOAT
);

-- Index untuk performa query frontend
CREATE INDEX idx_perawi_nama       ON perawi (nama_perawi);
CREATE INDEX idx_perawi_degree     ON perawi (degree DESC);
CREATE INDEX idx_edges_guru_id     ON edges (guru_id);
CREATE INDEX idx_edges_murid_id    ON edges (murid_id);
CREATE INDEX idx_edges_weight      ON edges (weight DESC);
"""

with engine.connect() as conn:
    conn.execute(text(schema_sql))
    conn.commit()

print("✅ Tabel 'perawi' dan 'edges' berhasil dibuat.")

In [ ]:
# ── Aktifkan akses publik (untuk frontend React dengan anon key) ─────────────
# Supabase mengaktifkan RLS secara default — tanpa policy ini,
# frontend tidak bisa membaca data sama sekali.

rls_sql = """
-- Aktifkan RLS
ALTER TABLE perawi ENABLE ROW LEVEL SECURITY;
ALTER TABLE edges   ENABLE ROW LEVEL SECURITY;

-- Izinkan siapa saja (anon) untuk membaca data (SELECT)
CREATE POLICY "public read perawi"
    ON perawi FOR SELECT
    USING (true);

CREATE POLICY "public read edges"
    ON edges FOR SELECT
    USING (true);
"""

with engine.connect() as conn:
    conn.execute(text(rls_sql))
    conn.commit()

print("✅ RLS policy berhasil dibuat — frontend React bisa membaca data.")

In [ ]:
# ── Push data ke Supabase ────────────────────────────────────────────────────

# 1. Tabel perawi
cols_perawi = [
    'Perawi_ID', 'Perawi', 'Nama_Perawi',
    'Degree', 'In_Degree', 'Out_Degree',
    'Degree_Centrality', 'Eigenvector_Centrality',
    'Closeness_Centrality', 'Betweenness_Centrality'
]
df_perawi = centrality_results[cols_perawi].copy()
df_perawi.columns = [c.lower() for c in df_perawi.columns]

df_perawi.to_sql(
    'perawi', engine,
    if_exists='append',
    index=False,
    chunksize=2000,
    method='multi'
)
print(f"✅ Tabel 'perawi': {len(df_perawi):,} baris berhasil disimpan.")

# 2. Tabel edges
cols_edges = ['Guru', 'Murid', 'Guru_ID', 'Murid_ID', 'Weight', 'Inverse_Weight']
df_edges = df[cols_edges].copy()
df_edges.columns = [c.lower() for c in df_edges.columns]

df_edges.to_sql(
    'edges', engine,
    if_exists='append',
    index=False,
    chunksize=5000,
    method='multi'
)
print(f"✅ Tabel 'edges': {len(df_edges):,} baris berhasil disimpan.")

In [ ]:
# ── Contoh query untuk frontend ─────────────────────────────────────────────
import pandas as pd

# 1. Top 10 perawi berdasarkan degree
q1 = "SELECT perawi_id, degree, degree_centrality, eigenvector_centrality FROM perawi ORDER BY degree DESC LIMIT 10"
print("=== Top 10 Perawi (Degree) ===")
display(pd.read_sql(q1, engine))

# 2. Ambil ego-network (1 hop) dari satu perawi untuk ditampilkan di graph
perawi_cari = "Abu Hurairah"
q2 = f"""
    SELECT e.guru_id AS guru, e.murid_id AS murid, e.weight
    FROM edges e
    WHERE e.guru_id = '{perawi_cari}' OR e.murid_id = '{perawi_cari}'
    ORDER BY e.weight DESC
    LIMIT 50
"""
print(f"\n=== Ego-Network '{perawi_cari}' (top 50 edge) ===")
display(pd.read_sql(q2, engine))

# 3. Cari perawi berdasarkan nama (untuk fitur search di frontend)
q3 = "SELECT perawi_id, degree FROM perawi WHERE perawi_id ILIKE '%Sufyan%' LIMIT 10"
print("\n=== Pencarian: 'Sufyan' ===")
display(pd.read_sql(q3, engine))