# Perhitungan Sentralitas

## Import Library

In [120]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [121]:
# Pengaturan tampilan
pd.set_option('display.max_colwidth', None)

# Membaca CSV
df = pd.read_csv('../data/processed/edge.csv')

# Konversi numerik
df['Weight'] = pd.to_numeric(df['Weight'])
df['Inverse_Weight'] = pd.to_numeric(df['Inverse_Weight'])

# Konversi Guru_Id dan Murid_Id ke integer (jika kolom ada)
for col in ['Edge_id', 'Guru_Id', 'Murid_Id']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Pembulatan
df['Inverse_Weight'] = df['Inverse_Weight'].round(8)

# Urutkan berdasarkan Weight terbesar
df = df.sort_values(by='Weight', ascending=False).reset_index(drop=True)

print(f"Total baris: {len(df):,}")
print(f"Kolom: {list(df.columns)}")
print(f"Tipe data:\n{df.dtypes}")

# Tampilkan 10 baris — format 8 desimal hanya pada Inverse_Weight
with pd.option_context('display.float_format', '{:.8f}'.format):
    display(df.head(10))

Total baris: 776,798
Kolom: ['Edge_id', 'Guru_Id', 'Guru', 'Nama_Guru', 'Murid_Id', 'Murid', 'Nama_Murid', 'Weight', 'Inverse_Weight']
Tipe data:
Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.00008814
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.00015620
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.00015649
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.00018328
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.00021445
5,6,1,ابو هريره,Abu Hurairah,34,ابو سلمه,Abu Salamah,4502,0.00022212
6,7,7,الزهري,Az-Zuhri,18,معمر,Ma'mar,4381,0.00022826
7,8,1,ابو هريره,Abu Hurairah,50,ابو صالح,Abu Shalih,3972,0.00025176
8,9,3,عائشه,Aisyah,57,عروه,Urwah,3953,0.00025297
9,10,3,عائشه,Aisyah,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,3950,0.00025316

## Load Data

In [122]:
print(df.dtypes)

Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

In [123]:
df.shape

(776798, 9)

In [124]:
# df["Inverse_Weight"] = df["Weight"].apply(lambda x: 1/x if x > 0 else 0)

In [125]:
df['Weight'] = pd.to_numeric(df['Weight'])
df['Inverse_Weight'] = pd.to_numeric(df['Inverse_Weight'])
print(df.dtypes)

Edge_id             Int64
Guru_Id             Int64
Guru                  str
Nama_Guru             str
Murid_Id            Int64
Murid                 str
Nama_Murid            str
Weight              int64
Inverse_Weight    float64
dtype: object

In [126]:
display(df)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.000088
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.000156
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.000156
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.000183
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.000214
...,...,...,...,...,...,...,...,...,...
776793,776794,7379,كيسان,Kysan,2764,محمد بن ربيعه,Muhammad bin Rby'h,1,1.000000
776794,776795,115,عليا,'lya,11903,صفوان بن عيسي الزهري,Shafwan bin Isa Az-Zuhri,1,1.000000
776795,776796,70179,ناسا من الصحابه,Nasa Mn Al-Shhabh,448,جابر بن زيد,Jabir bin Zaid,1,1.000000
776796,776797,7,الزهري,Az-Zuhri,2927,عبد الرزاق بن همام,Abdurrazzaq bin Hmam,1,1.000000
776797,776798,3232,لانس بن مالك,Lans bin Malik,3109,العلاء بن زياد,Al-'la' bin Zyad,1,1.000000

### Bentuk graph

In [127]:
G = nx.from_pandas_edgelist(
    df,
    source='Murid',
    target='Guru',
    edge_attr=['Weight', 'Inverse_Weight'],
    create_using=nx.DiGraph()
)

In [128]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 177047
Jumlah edge : 776798

In [129]:
display(df)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.000088
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.000156
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.000156
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.000183
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.000214
...,...,...,...,...,...,...,...,...,...
776793,776794,7379,كيسان,Kysan,2764,محمد بن ربيعه,Muhammad bin Rby'h,1,1.000000
776794,776795,115,عليا,'lya,11903,صفوان بن عيسي الزهري,Shafwan bin Isa Az-Zuhri,1,1.000000
776795,776796,70179,ناسا من الصحابه,Nasa Mn Al-Shhabh,448,جابر بن زيد,Jabir bin Zaid,1,1.000000
776796,776797,7,الزهري,Az-Zuhri,2927,عبد الرزاق بن همام,Abdurrazzaq bin Hmam,1,1.000000
776797,776798,3232,لانس بن مالك,Lans bin Malik,3109,العلاء بن زياد,Al-'la' bin Zyad,1,1.000000

In [130]:
# Hapus self-loop
G.remove_edges_from(nx.selfloop_edges(G))

In [131]:
print("Jumlah node setelah hapus self-loop:", G.number_of_nodes())
print("Jumlah edge setelah hapus self-loop:", G.number_of_edges())

Jumlah node setelah hapus self-loop: 177047
Jumlah edge setelah hapus self-loop: 776798

In [132]:
# Degree
degree_dict = dict(G.degree(weight='Weight'))
print("✅ Degree selesai")

# Degree Centrality
deg = nx.degree_centrality(G)
print("✅ Degree Centrality selesai.")

# In-Degree Centrality
if G.is_directed():
    in_deg = nx.in_degree_centrality(G)
    print("✅ In-Degree Centrality selesai.")
else:
    in_deg = {}

# Out-Degree Centrality
if G.is_directed():
    out_deg = nx.out_degree_centrality(G)
    print("✅ Out-Degree Centrality selesai.")
else:
    out_deg = {}

✅ Degree selesai
✅ Degree Centrality selesai.
✅ In-Degree Centrality selesai.
✅ Out-Degree Centrality selesai.

In [133]:
# === Eigenvector Centrality (Power Iteration)
try:
    eigenvector_centrality = nx.eigenvector_centrality(G, max_iter=5000, tol=1e-05, weight='Weight')
    print("✅ Eigenvector Centrality selesai.")
except nx.PowerIterationFailedConvergence:
    eigenvector_centrality = {}

# # === Eigenvector Centrality (NumPy version)
# try:
#     eigenvector_numpy_centrality = nx.eigenvector_centrality_numpy(G, weight='Weight')
#     print("✅ Eigenvector Numpy Centrality selesai.")
# except Exception as e:
#     eigenvector_numpy_centrality = {}
#     print(f"Proses gagal: {e}")

✅ Eigenvector Centrality selesai.

In [134]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 177047
Jumlah edge : 776798

In [135]:
print(f"Total edges dalam dataset lengkap: {len(df)}")
print(f"Unique Murid: {df['Murid'].nunique()}")
print(f"Unique Guru: {df['Guru'].nunique()}")
print(f"Total unique Perawi: {len(set(df['Murid'].unique()) | set(df['Guru'].unique()))}")
display(df.head(20))

Total edges dalam dataset lengkap: 776798
Unique Murid: 168903
Unique Guru: 153468
Total unique Perawi: 177047

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.000088
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.000156
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.000156
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.000183
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.000214
5,6,1,ابو هريره,Abu Hurairah,34,ابو سلمه,Abu Salamah,4502,0.000222
6,7,7,الزهري,Az-Zuhri,18,معمر,Ma'mar,4381,0.000228
7,8,1,ابو هريره,Abu Hurairah,50,ابو صالح,Abu Shalih,3972,0.000252
8,9,3,عائشه,Aisyah,57,عروه,Urwah,3953,0.000253
9,10,3,عائشه,Aisyah,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,3950,0.000253
10,11,20,جابر,Jabir,42,ابو الزبير,Abu Az-Zubair,3690,0.000271
11,12,12,انس,Anas,10,قتاده,Qatadah,3284,0.000305
12,13,1,ابو هريره,Abu Hurairah,102,الاعرج,Al-A'raj,3065,0.000326
13,14,5,شعبه,Syu'bah,73,محمد بن جعفر,Muhammad bin Ja'far,3047,0.000328
14,15,12,انس,Anas,70,ثابت,Tsabit,2751,0.000363
15,16,8,الاعمش,Al-A'masy,56,ابو معاويه,Abu Mu'awiyah,2737,0.000365
16,17,10,قتاده,Qatadah,5,شعبه,Syu'bah,2690,0.000372
17,18,38,ابو العباس محمد بن يعقوب,Abul Abbas Muhammad bin Ya'qub,14,ابو عبد الله الحافظ,Abu Abdullah Al-Hafizh,2487,0.000402
18,19,162,ابو عبد الله بن احمد بن حنبل,Abu Abdullah bin Ahmad bin Hanbal,77,عبد الله بن احمد بن حنبل,Abdullah bin Ahmad bin Hanbal,2476,0.000404
19,20,50,ابو صالح,Abu Shalih,8,الاعمش,Al-A'masy,2417,0.000414

In [136]:
# ==============================================
# Kombinasi Semua Centrality Measures
# ==============================================
import pandas as pd

# Build mapping nama Arab → Perawi_ID
guru_map  = df[['Guru', 'Guru_Id']].drop_duplicates().rename(columns={'Guru': 'Nama', 'Guru_Id': 'Perawi_ID'})
murid_map = df[['Murid', 'Murid_Id']].drop_duplicates().rename(columns={'Murid': 'Nama', 'Murid_Id': 'Perawi_ID'})
perawi_id_map = (
    pd.concat([guru_map, murid_map])
    .drop_duplicates('Nama')
    .set_index('Nama')['Perawi_ID']
    .to_dict()
)

# Build mapping nama Arab → nama Indonesia
guru_nama_map  = df[['Guru', 'Nama_Guru']].drop_duplicates().rename(columns={'Guru': 'Nama', 'Nama_Guru': 'Nama_Perawi'})
murid_nama_map = df[['Murid', 'Nama_Murid']].drop_duplicates().rename(columns={'Murid': 'Nama', 'Nama_Murid': 'Nama_Perawi'})
nama_perawi_map = (
    pd.concat([guru_nama_map, murid_nama_map])
    .drop_duplicates('Nama')
    .set_index('Nama')['Nama_Perawi']
    .to_dict()
)

# Semua nodes dari graph
all_nodes = list(G.nodes())

centrality_results = pd.DataFrame({
    'Perawi_ID'             : pd.array([perawi_id_map.get(n) for n in all_nodes], dtype='Int64'),
    'Perawi'                : all_nodes,
    'Nama_Perawi'           : [nama_perawi_map.get(n, '') for n in all_nodes],
    'Degree'                : [degree_dict.get(n, 0) for n in all_nodes],
    'Degree_Centrality'     : [deg.get(n, 0) for n in all_nodes],
    'In_Degree_Centrality'  : [in_deg.get(n, 0) for n in all_nodes],
    'Out_Degree_Centrality' : [out_deg.get(n, 0) for n in all_nodes],
    'Eigenvector_Centrality': [eigenvector_centrality.get(n, 0) for n in all_nodes],
})

centrality_results = centrality_results.round(8)
centrality_results = centrality_results.sort_values('Degree_Centrality', ascending=False).reset_index(drop=True)

# Format Eigenvector_Centrality tanpa scientific notation
centrality_results['Eigenvector_Centrality'] = (
    pd.to_numeric(centrality_results['Eigenvector_Centrality'], errors='coerce')
    .apply(lambda x: f"{x:.6f}")
)

display(centrality_results)


print(f"Total Perawi di graph : {G.number_of_nodes()}")
print(f"Total baris dataframe : {len(centrality_results)}")
print(f"NaN Perawi_ID         : {centrality_results['Perawi_ID'].isna().sum()}")
print(f"Nodes dengan Degree > 0: {(centrality_results['Degree'] > 0).sum()}")
print(f"\n{'='*80}")
display(centrality_results)

,Perawi_ID,Perawi,Nama_Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality
0,1,ابو هريره,Abu Hurairah,52846,0.027225,0.019927,0.007298,0.519539
1,6,سفيان,Sufyan,48556,0.026451,0.012951,0.013499,0.049429
2,5,شعبه,Syu'bah,50261,0.024400,0.011986,0.012415,0.056236
3,2,ابن عباس,Ibnu Abbas,39321,0.020390,0.015041,0.005349,0.265877
4,3,عائشه,Aisyah,32693,0.017312,0.013172,0.004140,0.483603
...,...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,Abu 'bydh Muslim bin Abu Krymh Al-Tmymy,1,0.000006,0.000000,0.000006,0.000000
177043,177285,جد بن فضيل,Jd bin Fdhyl,1,0.000006,0.000006,0.000000,0.000000
177044,177279,عمرو بن قره,Amru bin Qrh,1,0.000006,0.000000,0.000006,0.000000
177045,177276,يعلي بن سياه,Y'ly bin Syah,1,0.000006,0.000006,0.000000,0.000001
177046,177271,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.000006,0.000006,0.000000,0.000000

Total Perawi di graph : 177047
Total baris dataframe : 177047
NaN Perawi_ID         : 1
Nodes dengan Degree > 0: 177047

================================================================================

,Perawi_ID,Perawi,Nama_Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality
0,1,ابو هريره,Abu Hurairah,52846,0.027225,0.019927,0.007298,0.519539
1,6,سفيان,Sufyan,48556,0.026451,0.012951,0.013499,0.049429
2,5,شعبه,Syu'bah,50261,0.024400,0.011986,0.012415,0.056236
3,2,ابن عباس,Ibnu Abbas,39321,0.020390,0.015041,0.005349,0.265877
4,3,عائشه,Aisyah,32693,0.017312,0.013172,0.004140,0.483603
...,...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,Abu 'bydh Muslim bin Abu Krymh Al-Tmymy,1,0.000006,0.000000,0.000006,0.000000
177043,177285,جد بن فضيل,Jd bin Fdhyl,1,0.000006,0.000006,0.000000,0.000000
177044,177279,عمرو بن قره,Amru bin Qrh,1,0.000006,0.000000,0.000006,0.000000
177045,177276,يعلي بن سياه,Y'ly bin Syah,1,0.000006,0.000006,0.000000,0.000001
177046,177271,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.000006,0.000006,0.000000,0.000000

### Menghitung Closeness dan Betweenness dengan 50 ribu data

In [137]:
df_subset = df.head(100)
display(df_subset)

,Edge_id,Guru_Id,Guru,Nama_Guru,Murid_Id,Murid,Nama_Murid,Weight,Inverse_Weight
0,1,4,ابن عمر,Ibnu Umar,13,نافع,Nafi',11346,0.000088
1,2,18,معمر,Ma'mar,21,عبد الرزاق,Abdurrazzaq,6402,0.000156
2,3,48,ابو هشام بن عروه,Abu Hisyam bin Urwah,33,هشام بن عروه,Hisyam bin Urwah,6390,0.000156
3,4,2,ابن عباس,Ibnu Abbas,41,عكرمه,Ikrimah,5456,0.000183
4,5,2,ابن عباس,Ibnu Abbas,51,سعيد بن جبير,Sa'id bin Jubair,4663,0.000214
...,...,...,...,...,...,...,...,...,...
95,96,3,عائشه,Aisyah,321,عمره,'mrh,1132,0.000883
96,97,39,ايوب,Ayyub,72,حماد بن زيد,Hammad bin Zaid,1129,0.000886
97,98,245,ابو سفيان,Abu Sufyan,8,الاعمش,Al-A'masy,1126,0.000888
98,99,6,سفيان,Sufyan,208,الحميدي,Al-Hmydy,1110,0.000901
99,100,7,الزهري,Az-Zuhri,223,شعيب,Sy'yb,1097,0.000912

In [138]:
# Buat graph dari subset
G = nx.from_pandas_edgelist(
    df_subset,
    source='Murid',
    target='Guru',
    edge_attr=['Weight', 'Inverse_Weight'],
    create_using=nx.DiGraph()
)

print("✅ Graph berhasil dibuat dari subset.")

✅ Graph berhasil dibuat dari subset.

In [139]:
print("Jumlah node :", G.number_of_nodes())
print("Jumlah edge :", G.number_of_edges())

Jumlah node : 110
Jumlah edge : 100

In [140]:
from tqdm import tqdm
import pandas as pd

# ==========================================
# Hitung Closeness Centrality
# ==========================================

raw_closeness = {}

nodes = list(G.nodes())

for node in tqdm(nodes, desc="Closeness Centrality"):
    raw_closeness[node] = nx.closeness_centrality(
        G,
        u=node,
        distance="Inverse_Weight"
    )

print("✅ Closeness Centrality selesai.")

# ==========================================
# Normalisasi Min-Max (0 - 1)
# ==========================================

min_val = min(raw_closeness.values())
max_val = max(raw_closeness.values())

normalized_closeness = {
    node: (
        (value - min_val) / (max_val - min_val)
        if max_val > min_val else 1.0
    )
    for node, value in raw_closeness.items()
}

print("✅ Normalisasi selesai.")
display(normalized_closeness)

Closeness Centrality: 100%|██████████| 110/110 [00:00<00:00, 1651.51it/s]

✅ Closeness Centrality selesai.
✅ Normalisasi selesai.

{'نافع': 0.38031226048950056,
 'ابن عمر': 0.5446231351011951,
 'عبد الرزاق': 0.0,
 'معمر': 0.37307894204815906,
 'هشام بن عروه': 0.0,
 'ابو هشام بن عروه': 0.3723875694799824,
 'عكرمه': 0.0,
 'ابن عباس': 0.45359030742267004,
 'سعيد بن جبير': 0.0,
 'ابو سلمه': 0.4580735870087145,
 'ابو هريره': 1.0,
 'الزهري': 0.5558236231083608,
 'ابو صالح': 0.1954157498002161,
 'عروه': 0.43424700830363755,
 'عائشه': 0.9294551217052941,
 'ابو الزبير': 0.10319261005086139,
 'جابر': 0.1707340054726428,
 'قتاده': 0.4711647076431847,
 'انس': 0.6505647119859913,
 'الاعرج': 0.13543175706598445,
 'محمد بن جعفر': 0.0,
 'شعبه': 0.25310911197326935,
 'ثابت': 0.07383396144275399,
 'ابو معاويه': 0.0,
 'الاعمش': 0.15950002941734848,
 'ابو عبد الله الحافظ': 0.0,
 'ابو العباس محمد بن يعقوب': 0.14493006726832908,
 'عبد الله بن احمد بن حنبل': 0.0,
 'ابو عبد الله بن احمد بن حنبل': 0.14428773583223345,
 'ابو الزناد': 0.0,
 'ابن ابو نجيح': 0.24426446547377909,
 'مجاهد': 0.24650641222796932,
 'سعيد بن المسيب': 0.39388551240420167,
 'سفيان': 0.16896181718736578,
 'عمرو بن شعيب': 0.0,
 'ابو عمرو بن شعيب': 0.12738803556140962,
 'كيع': 0.0,
 'عبد الرحمن': 0.0,
 'ابراهيم': 0.3077106345387419,
 'ادم': 0.28263997446620615,
 'الربيع': 0.08916129492177426,
 'الشافعي': 0.14134880207608333,
 'عطاء': 0.11777590870546881,
 'جد عمرو بن شعيب': 0.15185253999354398,
 'انس بن مالك': 0.3773965323380961,
 'سعيد': 0.0,
 'عبيد الله': 0.0,
 'ابن جريج': 0.06713237650383895,
 'حميد': 0.0,
 'رقاء': 0.25902086867907,
 'علقمه': 0.2679805774111014,
 'يونس': 0.07465019823212037,
 'ابن شهاب': 0.29670646898731423,
 'يونس بن حبيب': 0.08141003429342913,
 'ابو داود': 0.18910608368354892,
 'مالك': 0.07039650493219754,
 'الحسن': 0.35974844277306006,
 'محمد بن عمرو': 0.0,
 'اسرائيل': 0.0,
 'ابو اسحاق': 0.25700819920094903,
 'سالم': 0.3634286406847462,
 'عبد الله بن عمر': 0.2851211896075463,
 'همام': 0.0,
 'ابو العباس': 0.0,
 'عبيد الله بن عمر': 0.0,
 'جعفر بن محمد': 0.0,
 'ابو جعفر بن محمد': 0.08875255977447828,
 'ابو سالم': 0.2878706284785209,
 'ايوب': 0.06579236654991583,
 'جابر بن عبد الله': 0.1191927623462695,
 'عبد الله بن دينار': 0.0,
 'عبد الله بن جعفر': 0.0,
 'ابو قلابه': 0.09942321796857768,
 'الاسود': 0.24570095727482402,
 'عروه بن الزبير': 0.0,
 'عبد الله': 0.2695617194053327,
 'سهيل بن ابو صالح': 0.0,
 'ابو سهيل بن ابو صالح': 0.07581563638103982,
 'عبد الله بن احمد': 0.0,
 'ابو عبد الله بن احمد': 0.07558258744753303,
 'ابن وهب': 0.0,
 'طاوس': 0.0,
 'محمد بن يوسف': 0.06998814703584075,
 'محمد بن اسماعيل': 0.0971726611382637,
 'حماد بن سلمه': 0.0,
 'عبد الوارث بن سفيان': 0.0,
 'قاسم بن اصبغ': 0.07365944175230989,
 'عبيد بن غنام': 0.0,
 'ابو بكر بن ابو شيبه': 0.07325204357784958,
 'مسروق': 0.0,
 'منصور': 0.13605606892408037,
 'القعنبي': 0.0,
 'احمد بن عبد الله النعيمي': 0.0,
 'يحيي بن ابو كثير': 0.0,
 'سعيد بن ابو عروبه': 0.0,
 'الحكم': 0.19204674405593683,
 'ابو وائل': 0.0,
 'عمرو بن الحارث': 0.06759883854898378,
 'محمد بن بكر': 0.0,
 'زيد بن اسلم': 0.0,
 'عطاء بن يسار': 0.06713237650383895,
 'هشام': 0.0,
 'ابو هشام': 0.06695805077204069,
 'سفيان بن عيينه': 0.0,
 'عقيل': 0.0,
 'عمره': 0.0,
 'حماد بن زيد': 0.0,
 'ابو سفيان': 0.10884575869538551,
 'الحميدي': 0.0,
 'شعيب': 0.0}

In [141]:
import networkx as nx
from tqdm import tqdm

def betweenness_centrality_with_progress(G, normalized=True, weight=None):
    nodes = list(G.nodes())
    bet = dict.fromkeys(nodes, 0.0)

    for s in tqdm(nodes, desc="Betweenness Centrality (Nodes)"):
        # hitung betweenness subset: dari source s ke semua node
        contrib = nx.betweenness_centrality_subset(
            G, sources=[s], targets=nodes,
            normalized=normalized, weight=weight
        )
        # gabungkan kontribusi
        for n, v in contrib.items():
            bet[n] += v

    return bet


# =====================
# Pemakaian
# =====================
bet_node = betweenness_centrality_with_progress(G, normalized=True, weight="Inverse_weight")

print("✅ Betweenness selesai.")

Betweenness Centrality (Nodes): 100%|██████████| 110/110 [00:00<00:00, 18396.80it/s]

✅ Betweenness selesai.

In [142]:
# ==============================================
# Kombinasi Semua Centrality Measures
# ==============================================
import pandas as pd

# Semua nodes dari FULL graph (bukan subset)
# degree_dict dihitung dari full graph → 177047 nodes
all_nodes = list(degree_dict.keys())

centrality_results = pd.DataFrame({
    'Perawi_ID'             : pd.array([perawi_id_map.get(n) for n in all_nodes], dtype='Int64'),
    'Perawi'                : all_nodes,
    'Nama_Perawi'           : [nama_perawi_map.get(n, '') for n in all_nodes],
    'Degree'                : [degree_dict.get(n, 0) for n in all_nodes],
    'Degree_Centrality'     : [deg.get(n, 0) for n in all_nodes],
    'In_Degree_Centrality'  : [in_deg.get(n, 0) for n in all_nodes],
    'Out_Degree_Centrality' : [out_deg.get(n, 0) for n in all_nodes],
    'Eigenvector_Centrality': [eigenvector_centrality.get(n, 0) for n in all_nodes],
    'Closeness_Centrality'  : [normalized_closeness.get(n, 0) for n in all_nodes],
    'Betweenness_Centrality': [bet_node.get(n, 0) for n in all_nodes],
})

centrality_results = centrality_results.round(8)
centrality_results = centrality_results.sort_values('Degree_Centrality', ascending=False).reset_index(drop=True)

# Format Eigenvector_Centrality tanpa scientific notation
centrality_results['Eigenvector_Centrality'] = (
    pd.to_numeric(centrality_results['Eigenvector_Centrality'], errors='coerce')
    .apply(lambda x: f"{x:.6f}")
)

display(centrality_results)


print(f"Total Perawi di full graph : {len(all_nodes)}")
print(f"Total baris dataframe      : {len(centrality_results)}")
print(f"NaN Perawi_ID              : {centrality_results['Perawi_ID'].isna().sum()}")
print(f"Nodes dengan Degree > 0    : {(centrality_results['Degree'] > 0).sum()}")
print(f"Nodes dengan Closeness > 0 : {(centrality_results['Closeness_Centrality'] > 0).sum()}")
print(f"Nodes dengan Betweenness > 0: {(centrality_results['Betweenness_Centrality'] > 0).sum()}")
display(centrality_results)

,Perawi_ID,Perawi,Nama_Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality,Closeness_Centrality,Betweenness_Centrality
0,1,ابو هريره,Abu Hurairah,52846,0.027225,0.019927,0.007298,0.519539,1.000000,0.000000
1,6,سفيان,Sufyan,48556,0.026451,0.012951,0.013499,0.049429,0.168962,0.003058
2,5,شعبه,Syu'bah,50261,0.024400,0.011986,0.012415,0.056236,0.253109,0.002548
3,2,ابن عباس,Ibnu Abbas,39321,0.020390,0.015041,0.005349,0.265877,0.453590,0.000000
4,3,عائشه,Aisyah,32693,0.017312,0.013172,0.004140,0.483603,0.929455,0.000000
...,...,...,...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,Abu 'bydh Muslim bin Abu Krymh Al-Tmymy,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177043,177285,جد بن فضيل,Jd bin Fdhyl,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000
177044,177279,عمرو بن قره,Amru bin Qrh,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177045,177276,يعلي بن سياه,Y'ly bin Syah,1,0.000006,0.000006,0.000000,0.000001,0.000000,0.000000
177046,177271,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000

Total Perawi di full graph : 177047
Total baris dataframe      : 177047
NaN Perawi_ID              : 1
Nodes dengan Degree > 0    : 177047
Nodes dengan Closeness > 0 : 64
Nodes dengan Betweenness > 0: 35

,Perawi_ID,Perawi,Nama_Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality,Closeness_Centrality,Betweenness_Centrality
0,1,ابو هريره,Abu Hurairah,52846,0.027225,0.019927,0.007298,0.519539,1.000000,0.000000
1,6,سفيان,Sufyan,48556,0.026451,0.012951,0.013499,0.049429,0.168962,0.003058
2,5,شعبه,Syu'bah,50261,0.024400,0.011986,0.012415,0.056236,0.253109,0.002548
3,2,ابن عباس,Ibnu Abbas,39321,0.020390,0.015041,0.005349,0.265877,0.453590,0.000000
4,3,عائشه,Aisyah,32693,0.017312,0.013172,0.004140,0.483603,0.929455,0.000000
...,...,...,...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,Abu 'bydh Muslim bin Abu Krymh Al-Tmymy,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177043,177285,جد بن فضيل,Jd bin Fdhyl,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000
177044,177279,عمرو بن قره,Amru bin Qrh,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177045,177276,يعلي بن سياه,Y'ly bin Syah,1,0.000006,0.000006,0.000000,0.000001,0.000000,0.000000
177046,177271,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000

In [143]:
display(centrality_results)

,Perawi_ID,Perawi,Nama_Perawi,Degree,Degree_Centrality,In_Degree_Centrality,Out_Degree_Centrality,Eigenvector_Centrality,Closeness_Centrality,Betweenness_Centrality
0,1,ابو هريره,Abu Hurairah,52846,0.027225,0.019927,0.007298,0.519539,1.000000,0.000000
1,6,سفيان,Sufyan,48556,0.026451,0.012951,0.013499,0.049429,0.168962,0.003058
2,5,شعبه,Syu'bah,50261,0.024400,0.011986,0.012415,0.056236,0.253109,0.002548
3,2,ابن عباس,Ibnu Abbas,39321,0.020390,0.015041,0.005349,0.265877,0.453590,0.000000
4,3,عائشه,Aisyah,32693,0.017312,0.013172,0.004140,0.483603,0.929455,0.000000
...,...,...,...,...,...,...,...,...,...,...
177042,70177,ابو عبيده مسلم بن ابو كريمه التميمي,Abu 'bydh Muslim bin Abu Krymh Al-Tmymy,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177043,177285,جد بن فضيل,Jd bin Fdhyl,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000
177044,177279,عمرو بن قره,Amru bin Qrh,1,0.000006,0.000000,0.000006,0.000000,0.000000,0.000000
177045,177276,يعلي بن سياه,Y'ly bin Syah,1,0.000006,0.000006,0.000000,0.000001,0.000000,0.000000
177046,177271,عباد بن عمرو السلمي,'bad bin Amru Al-Slmy,1,0.000006,0.000006,0.000000,0.000000,0.000000,0.000000

In [144]:
# centrality_results.to_csv("../data/processed/centrality.csv", index=False, encoding='utf-8-sig')