# Load data Sanadset

## Import Library

In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import ast
import re
from collections import Counter

## Load Data

In [47]:
# pd.set_option('display.max_colwidth', None)

df = pd.read_csv('../data/raw/sanadset.csv', header=None)
df.columns = ['Hadith', 'Book', 'Num_hadith', 'Matn', 'Sanad', 'Sanad_Length']
df = df.iloc[1:].reset_index(drop=True)

# Pastikan kolom Sanad ada
assert 'Sanad' in df.columns, "❌ Kolom 'Sanad' tidak ditemukan!"

print(f" Data loaded: {len(df)} baris")
print(f" Kolom: {df.columns.tolist()}")
print(f" Tipe data: {df.dtypes.to_dict()}")

print(f"\n Sample data:")
print(df.head(3))

df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5404\1846584940.py:3: DtypeWarning: Columns (0: 2, 1: 5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/sanadset.csv', header=None)

 Data loaded: 650986 baris
 Kolom: ['Hadith', 'Book', 'Num_hadith', 'Matn', 'Sanad', 'Sanad_Length']
 Tipe data: {'Hadith': <StringDtype(storage='python', na_value=nan)>, 'Book': <StringDtype(storage='python', na_value=nan)>, 'Num_hadith': dtype('O'), 'Matn': <StringDtype(storage='python', na_value=nan)>, 'Sanad': <StringDtype(storage='python', na_value=nan)>, 'Sanad_Length': dtype('O')}

 Sample data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Hadith  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ </NAR>  ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ </NAR>  , عَنْ <NAR> عَبْدِ اللَّهِ بْنِ عَبَّاسٍ </NAR> </SANAD> <MATN>   ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : " نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "  . </MATN>
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <MATN> وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، قَالَ : " إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَلِكُلِّ امْرِئٍ مَا نَوَى "  . </MATN>
2  حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR>  ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR>  ، عَنْ <NAR> عَائِشَةَ </NAR> </SANAD> <MATN>   ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : " أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ " ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا  ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي . </MATN>

                  Book Num_hadith  \
0  مسند الربيع بن حبيب          1
1  مسند الربيع بن حبيب          2
2  مسند الربيع بن حبيب          3

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Matn  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : " نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "  .
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                     وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، قَالَ : " إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَلِكُلِّ امْرِئٍ مَا نَوَى "  .
2    ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : " أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ " ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا  ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي .

                                                                                                                                 Sanad  \
0  ['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ', 'جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ', 'عَبْدِ اللَّهِ بْنِ عَبَّاسٍ']
1                                                                                                                             No SANAD
2                                                                             ['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'عَائِشَةَ']

  Sanad_Length
0            3
1            0
2            3

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length
0,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ </NAR> , عَنْ <NAR> عَبْدِ اللَّهِ بْنِ عَبَّاسٍ </NAR> </SANAD> <MATN> ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" . </MATN>",مسند الربيع بن حبيب,1,"، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" .","['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ', 'جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ', 'عَبْدِ اللَّهِ بْنِ عَبَّاسٍ']",3
1,"<MATN> وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، قَالَ : "" إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَلِكُلِّ امْرِئٍ مَا نَوَى "" . </MATN>",مسند الربيع بن حبيب,2,"وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْهُ عَلَيْهِ السَّلامُ ، قَالَ : "" إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَلِكُلِّ امْرِئٍ مَا نَوَى "" .",No SANAD,0
2,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> ، عَنْ <NAR> عَائِشَةَ </NAR> </SANAD> <MATN> ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي . </MATN>",مسند الربيع بن حبيب,3,"، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي .","['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'عَائِشَةَ']",3
3,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> </SANAD> <MATN> ، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" . </MATN>",مسند الربيع بن حبيب,4,"، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" .","['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ']",2
4,"<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرُ بْنُ زَيْدٍ </NAR> ، عَنْ <NAR> أَبِي هُرَيْرَةَ </NAR> </SANAD> <MATN> ، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ : "" إِذَا قَرَأْتَ الْقُرْآنَ فَرَتِّلْهُ تَرْتِيلا ، وَتَغَنَّوْا بِهِ , فَإِنَّ اللَّهَ يُحِبُّ أَنْ تَسْمَعَ الْمَلائِكَةُ لِذِكْرِهِ "" . </MATN>",مسند الربيع بن حبيب,5,"، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ : "" إِذَا قَرَأْتَ الْقُرْآنَ فَرَتِّلْهُ تَرْتِيلا ، وَتَغَنَّوْا بِهِ , فَإِنَّ اللَّهَ يُحِبُّ أَنْ تَسْمَعَ الْمَلائِكَةُ لِذِكْرِهِ "" .","['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أَبِي هُرَيْرَةَ']",3
...,...,...,...,...,...,...
650981,"وعن وعن <SANAD> <NAR> أبي الخير </NAR> ، قال : قال <NAR> كعب </NAR> </SANAD> <MATN> "" نهر النيل نهر العسل في الجنة ، ونهر دجلة نهر اللبن في الجنة ، ونهر الفرات نهر الخمر في الجنة ، ونهر سيحان نهر الماء في الجنة ، قال : فأطفأ الله نورهن ليصيرهن إلى الجنة "" . رواه الحارث بن أبي أسامة موقوفًا ، ورواته ثقات . </MATN>",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6205,""" نهر النيل نهر العسل في الجنة ، ونهر دجلة نهر اللبن في الجنة ، ونهر الفرات نهر الخمر في الجنة ، ونهر سيحان نهر الماء في الجنة ، قال : فأطفأ الله نورهن ليصيرهن إلى الجنة "" . رواه الحارث بن أبي أسامة موقوفًا ، ورواته ثقات .","['أبي الخير', 'كعب']",2
650982,"وعن <SANAD> <NAR> ابن عمر </NAR> </SANAD> <MATN> ، رَضِيَ اللَّهُ عنهما ، قال : "" ألا أخبركم بأسفل لأهل الجنة ؟ قالوا : بلى ، فقال : رجل يدخل من باب الجنة ، فتتلقاه غلمانه ، فيقولون : مرحبًا بك يا سيدنا ، قد آن لك أن تثوب ، قال : فتمد له الزرابي أربعين سنة ، ثم ينظر عن يمينه وعن شماله فيرى الجنان ، فيقول : لمن ما هنا ؟ فيقال : لك ، حتى إذا انتهى رفعت له ياقوتة حمراء ، أو زمردة خضراء ، لها سبعون شعبًا ، في كل شعب سبعون غرفة ، في كل غرفة سبعون بابًا ، فيقال له : اقرأ وارق ، قال : فيرتقي ، حتى إذا انتهى إلى سرير ملكه اتكأ عليه ، سعته ميل في ميل ، وله عنه فضول ، فيسعى إليه بسبعين ألف صحفة من ذهب ، ليس فيها صحفة من لون صحابتها ، فيجد لذة آخرها كما يجد أولها ، ثم يسع عليه بألوان الأشربة ، فيشرب منها ما اشتهى ، ثم يقال للغلمان : ذروه وأزواجه "" . قال ابن شهاب : فأحسبه ، قال : "" فتتجافى عنه الغلمان ، فإذا الحور قاعدة على سرير ملكها ، فيرى مُخ ساقيها من وراء اللحم والدم ، فيقول لها : من أنت ؟ فتقول : أنا من الحور العين اللاتي خبئن لك ، فينظر إليها أربعين سنة لا يرفع بصره عنها ، ثم يرفع بصره إلى الغرف فوقه ، فإذا أخرى أجمل منها ، فتقول له : أما آن لنا أن يكون لنا منك نصيب ، فيرتقي إليها فينظر إليها أربعين سنة لا يصرف بصره عنها ، حتى إذا بلغ النعيم منهم كل مبلغ ، وظنوا أن لا أفضل منه ، تجلى لهم الرب تبارك وتعالى ، فنظروا إلى وجه الرحمن عز وجل ، فنسوا كل نعيم عاينوه حين أنظروا وجه الرحمن عز وجل ، فيقول : يا أهل الجنة ، هللوني ، فيتجاوبون بالتهليل ، فيقول : يا داود ، قم فمجدني كما كنت تمجدني في الدنيا ، فيمجد داود ربه عز وجل "" . قال أحمد بن يونس : قلت لابن شهاب : حديث خالد بن دينار في ذكر الجنة مرفوع ؟ قال : نعم . رواه عبد بن حميد ، وابن أبي الدنيا ، قال الحافظ المنذري رحمة الله : وفي إسناده من لا أعرفه الآن . </MATN>",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6206,"، رَضِيَ اللَّهُ عنهما ، قال : "" ألا أخبركم بأسفل لأهل الجنة ؟ قالوا : بلى ، فقال : رجل يدخل من باب الجنة ، فتتلقاه غلمانه ، فيقولون : مرحبًا بك يا سيدنا ، قد آن لك أن تثوب ، قال : فتمد له الزرابي أربعين سنة ، ثم ينظر عن يمينه وعن شماله فيرى الجنان ، فيقول : لمن ما هنا ؟ فيقال : لك ، حتى إذا انتهى رفعت له ياقوتة حمراء ، أو زمردة خضراء ، لها سبعون شعبًا ، في كل شعب سبعون غرفة ، في كل غرفة سبعون بابًا ، فيقال له : اقرأ وارق ، قال : فيرتقي ، حتى إذا انتهى إلى سرير ملكه اتكأ عليه ، سعته ميل في ميل ، وله عنه فضول ، فيسعى إليه بسبعين ألف صحفة من ذهب ، ليس فيها صحفة من لون صحابتها ، فيجد لذة آخرها كما يجد أولها ، ثم يسع عليه بألوان الأشربة ، فيشرب منها ما اشتهى ، ثم يقال للغلمان : ذروه وأزواجه "" . قال ابن شهاب : فأحسبه ، قال : "" فتتجافى عنه الغلمان ، فإذا الحور قاعدة على سرير ملكها ، فيرى مُخ ساقيها من وراء اللحم والدم ، فيقول لها : من أنت ؟ فتقول : أنا من الحور العين اللاتي خبئن لك ، فينظر إليها أربعين سنة لا يرفع بصره عنها ، ثم يرفع بصره إلى الغرف فوقه ، فإذا أخرى أجمل منها ، فتقول له : أما آن لنا أن يكون لنا منك نصيب ، فيرتقي إليها فينظر إليها أربعين سنة لا يصرف بصره عنها ، حتى إذا بلغ النعيم منهم كل مبلغ ، وظنوا أن لا أفضل منه ، تجلى لهم الرب تبارك وتعالى ، فنظروا إلى وجه الرحمن عز وجل ، فنسوا كل نعيم عاينوه حين أنظروا وجه الرحمن عز وجل ، فيقول : يا أهل الجنة ، هللوني ، فيتجاوبون بالتهليل ، فيقول : يا داود ، قم فمجدني كما كنت تمجدني في الدنيا ، فيمجد داود ربه عز وجل "" . قال أحمد بن يونس : قلت لابن شهاب : حديث خالد بن دينار في ذكر الجنة مرفوع ؟ قال : نعم . رواه عبد بن حميد ، وابن أبي الدنيا ، قال الحافظ المنذري رحمة الله : وفي إسناده من لا أعرفه الآن .",['ابن عمر'],1
650983,"- وَعَنْ - وَعَنْ مُجَاهِدٍ ، قَالَ : "" مَرَّ رَجُلٌ <SANAD> <NAR> بِابْنِ عَبَّاسٍ </NAR> </SANAD> <MATN> ، فَقَالَ : إِنَّ هَذَا الرَّجُلَ يُحِبُّنِي ، قَالُوا : وَمَا يُدْرِيكَ يَابْنَ عَبَّاسٍ ؟ قَالَ : لِأَنِّي أُحِبُّهُ "" . رَوَاهُ أَبُو يَعْلَى الْمَوْصِلِيُّ ، مَوْقُوفًا . </MATN>",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6207,"، فَقَالَ : إِنَّ هَذَا الرَّجُلَ يُحِبُّنِي ، قَالُوا : وَمَا يُدْرِيكَ يَابْنَ عَبَّاسٍ ؟ قَالَ : لِأَنِّي أُحِبُّهُ "" . رَوَاهُ أَبُو يَعْلَى الْمَوْصِلِيُّ ، مَوْقُوفًا .",['بِابْنِ عَبَّاسٍ'],1
650984,"- وَعَنْ - وَعَنْ أَبِي ظَبْيَانَ ، عَنِ <SANAD> <NAR> ابْنِ عَبَّاسٍ </NAR> </SANAD> <MATN> , رَضِيَ اللَّهُ عَنْهُمَا , "" لَيْسَ فِي الدُّنْيَا مِمَّا فِي الْجَنَّةِ شَيء إِلَّا الْأَسْمَاءَ "" . رَوَاهُ مُسَدَّدٌ مَوْقُوفًا ، وَرُوَاتُهُ ثِقَاتٌ . </MATN>",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6208,", رَضِيَ اللَّهُ عَنْهُمَا , "" لَيْسَ فِي الدُّنْيَا مِمَّا فِي الْجَنَّةِ شَيء إِلَّا الْأَسْمَاءَ "" . رَوَاهُ مُسَدَّدٌ مَوْقُوفًا ، وَرُوَاتُهُ ثِقَاتٌ .",['ابْنِ عَبَّاسٍ'],1
650985,"- وَعَنْ - وَعَنْ أَسْلَمَ ، عَنِ امْرَأَتِهِ ، قَالَتْ : "" خَطَبَنَا <SANAD> <NAR> أَبُو مُوسَى </NAR> </SANAD> <MATN> رَضِيَ اللَّهُ عَنْهُ ، فَبَيْنَا نَحْنُ كَذَلِكَ إِذْ صَرَفُوا أَبْصَارَهُمْ ، أَوْ شَخَصُوا أَبْصَارَهُمْ ، قَالَ : مَا صَرَفَ أَبْصَارَهُمْ ؟ قَالُوا : الْهِلَالُ ، قَالَ : فَذَلِكَ الَّذِي شَخَصَ أَبْصَارَهُمْ ، أَوْ صَرَفَ أَبْصَارَهُمْ ؟ قَالُوا : نَعَمْ ، قَالَ : فَكَيْفَ إِذَا أَبْصَرْتُمُ اللَّهَ تَبَارَكَ وَتَعَالَى جَهْرَةً "" . رَوَاهُ مُسَدَّدٌ ، عَنْ يَحْيَى ، عَنِ التَّيْمِيِّ ، عَنْهُ ، بِهِ ، وَفِي الْبَابِ حَدِيثُ أَنَسِ بْنِ مَالِكٍ الطَّوِيلُ ، وَتَقَدَّمَ فِي أَوَّلِ كِتَابِ الْجُمُعَةِ ، وَفِيهِ حَدِيثُ عَلِيِّ بْنِ أَبِي طَالِبٍ ، وَتَقَدَّمَ فِي بَابِ الْمُتَحَابِّينَ . "" فَيَقُولُونَ : لَبَّيْكَ رَبَّنَا ، قَالَ : فَيُقَالُ : هَلْ تَعْرِفُونَ هَذَا ؟ فَيَقُولُونَ : نَعَمْ رَبَّنَا هَذَا الْمَوْتُ ، ثُمَّ يُنَادِي مُنَادٍ : يَا أَهْلَ النَّارِ ، فَيَقُولُونَ : لَبَّيْكَ رَبَّنَا ، قَالَ : فَيُقَالُ : هَلْ تَعْرِفُونَ هَذَا ؟ فَيَقُولُونَ : نَعَمْ رَبَّنَا هَذَا الْمَوتُ ، فَيُذْبَحُ كَمَا تُذْبَحُ الشَّاةُ ، فَيَأْمَنُ هَؤُلَاءِ ، وَيَنْقَطِعُ رَجَاءُ هَؤُلَاءِ "" . رَوَاهُ أَبُو يَعْلَى ، وَالطَّبَرَانِيُّ ، وَالْبَزَّارُ ، وَأَسَانِيدُهُمْ صِحَاحٌ . وَلَهُ شَاهِدٌ فِي الصَّحِيحَيْنِ مِنْ حَدِيثِ أَبِي سَعِيدٍ الْخُدْرِيِّ ، وَمِنْ حَدِيثِ ابْنِ عُمَرَ . وَرَوَاهُ ابْنُ حِبَّانَ فِي صَحِيحِهِ مِنْ حَدِيثِ أَبِي هُرَيْرَةَ . </MATN>",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6209,"رَضِيَ اللَّهُ عَنْهُ ، فَبَيْنَا نَحْنُ كَذَلِكَ إِذْ صَرَفُوا أَبْصَارَهُمْ ، أَوْ شَخَصُوا أَبْصَارَهُمْ ، قَالَ : مَا صَرَفَ أَبْصَارَهُمْ ؟ قَالُوا : الْهِلَالُ ، قَالَ : فَذَلِكَ الَّذِي شَخَصَ أَبْصَارَهُمْ ، أَوْ صَرَفَ أَبْصَارَهُمْ ؟ قَالُوا : نَعَمْ ، قَالَ : فَكَيْفَ إِذَا أَبْصَرْتُمُ اللَّهَ تَبَارَكَ وَتَعَالَى جَهْرَةً "" . رَوَاهُ مُسَدَّدٌ ، عَنْ يَحْيَى ، عَنِ التَّيْمِيِّ ، عَنْهُ ، بِهِ ، وَفِي الْبَابِ حَدِيثُ أَنَسِ بْنِ مَالِكٍ الطَّوِيلُ ، وَتَقَدَّمَ فِي أَوَّلِ كِتَابِ الْجُمُعَةِ ، وَفِيهِ حَدِيثُ عَلِيِّ بْنِ أَبِي طَالِبٍ ، وَتَقَدَّمَ فِي بَابِ الْمُتَحَابِّينَ . "" فَيَقُولُونَ : لَبَّيْكَ رَبَّنَا ، قَالَ : فَيُقَالُ : هَلْ تَعْرِفُونَ هَذَا ؟ فَيَقُولُونَ : نَعَمْ رَبَّنَا هَذَا الْمَوْتُ ، ثُمَّ يُنَادِي مُنَادٍ : يَا أَهْلَ النَّارِ ، فَيَقُولُونَ : لَبَّيْكَ رَبَّنَا ، قَالَ : فَيُقَالُ : هَلْ تَعْرِفُونَ هَذَا ؟ فَيَقُولُونَ : نَعَمْ رَبَّنَا هَذَا الْمَوتُ ، فَيُذْبَحُ كَمَا تُذْبَحُ الشَّاةُ ، فَيَأْمَنُ هَؤُلَاءِ ، وَيَنْقَطِعُ رَجَاءُ هَؤُلَاءِ "" . رَوَاهُ أَبُو يَعْلَى ، وَالطَّبَرَانِيُّ ، وَالْبَزَّارُ ، وَأَسَانِيدُهُمْ صِحَاحٌ . وَلَهُ شَاهِدٌ فِي الصَّحِيحَيْنِ مِنْ حَدِيثِ أَبِي سَعِيدٍ الْخُدْرِيِّ ، وَمِنْ حَدِيثِ ابْنِ عُمَرَ . وَرَوَاهُ ابْنُ حِبَّانَ فِي صَحِيحِهِ مِنْ حَدِيثِ أَبِي هُرَيْرَةَ .",['أَبُو مُوسَى'],1

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 650986 entries, 0 to 650985
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Hadith        650986 non-null  str
 1   Book          650986 non-null  str
 2   Num_hadith    650986 non-null  object
 3   Matn          650986 non-null  str
 4   Sanad         650986 non-null  str
 5   Sanad_Length  650986 non-null  object
dtypes: object(2), str(4)
memory usage: 29.8+ MB

# Pembersihan Data Sanadset

### Menghapus No Sanad di Kolom Sanad

In [49]:
# Hapus baris 'No SANAD'
df = df[df['Sanad'] != 'No SANAD'].copy()

# Print jumlah data setelah filtering
print("Jumlah data setelah No SANAD dihapus:", len(df))
df.head(5)

Jumlah data setelah No SANAD dihapus: 491428

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length
0,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ </NAR> , عَنْ <NAR> عَبْدِ اللَّهِ بْنِ عَبَّاسٍ </NAR> </SANAD> <MATN> ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" . </MATN>",مسند الربيع بن حبيب,1,"، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" .","['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ', 'جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ', 'عَبْدِ اللَّهِ بْنِ عَبَّاسٍ']",3
2,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> ، عَنْ <NAR> عَائِشَةَ </NAR> </SANAD> <MATN> ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي . </MATN>",مسند الربيع بن حبيب,3,"، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي .","['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'عَائِشَةَ']",3
3,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> </SANAD> <MATN> ، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" . </MATN>",مسند الربيع بن حبيب,4,"، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" .","['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ']",2
4,"<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرُ بْنُ زَيْدٍ </NAR> ، عَنْ <NAR> أَبِي هُرَيْرَةَ </NAR> </SANAD> <MATN> ، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ : "" إِذَا قَرَأْتَ الْقُرْآنَ فَرَتِّلْهُ تَرْتِيلا ، وَتَغَنَّوْا بِهِ , فَإِنَّ اللَّهَ يُحِبُّ أَنْ تَسْمَعَ الْمَلائِكَةُ لِذِكْرِهِ "" . </MATN>",مسند الربيع بن حبيب,5,"، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَالَ : "" إِذَا قَرَأْتَ الْقُرْآنَ فَرَتِّلْهُ تَرْتِيلا ، وَتَغَنَّوْا بِهِ , فَإِنَّ اللَّهَ يُحِبُّ أَنْ تَسْمَعَ الْمَلائِكَةُ لِذِكْرِهِ "" .","['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أَبِي هُرَيْرَةَ']",3
5,"<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرُ بْنُ زَيْدٍ </NAR> ، عَنْ <NAR> أَبِي سَعِيدٍ الْخُدْرِيِّ </NAR> </SANAD> <MATN> ، قَالَ : قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : "" مَثَلُ صَاحِبِ الْقُرْآنِ ، كَمَثَلِ صَاحِبِ الإِبِلِ الْمُعَقَّلَةِ ، إِنْ عَاهَدَ عَلَيْهَا أَمْسَكَهَا ، وَإِنْ أَطْلَقَهَا ذَهَبَتْ "" . </MATN>",مسند الربيع بن حبيب,6,"، قَالَ : قَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : "" مَثَلُ صَاحِبِ الْقُرْآنِ ، كَمَثَلِ صَاحِبِ الإِبِلِ الْمُعَقَّلَةِ ، إِنْ عَاهَدَ عَلَيْهَا أَمْسَكَهَا ، وَإِنْ أَطْلَقَهَا ذَهَبَتْ "" .","['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أَبِي سَعِيدٍ الْخُدْرِيِّ']",3

### Ubah Sanad dari String ke List

In [50]:
# Ubah nilai string yang merepresentasikan list menjadi object list Python

def parse_list(value):
    if isinstance(value, str):
        try:
            return ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return value
    return value

df['Sanad'] = df['Sanad'].apply(parse_list)

print(df['Sanad'].head())
print(type(df['Sanad'].iloc[0]))

0    [أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ, جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ, عَبْدِ اللَّهِ بْنِ عَبَّاسٍ]
2                                                                               [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِشَةَ]
3                                                                                          [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]
4                                                                        [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي هُرَيْرَةَ]
5                                                              [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي سَعِيدٍ الْخُدْرِيِّ]
Name: Sanad, dtype: object
<class 'list'>

### Menghilangkan Harakat

In [51]:
def remove_harakat(text): ## Remove Arabic diacritics (harakat)

    # Regex karakter harakat Arab
    pattern = r'[\u064B-\u065F\u0670\u06D6-\u06ED]'
    # Jika data berupa list
    if isinstance(text, list):
        return [
            re.sub(pattern, '', str(t))
            for t in text]
    # Jika data berupa string
    elif isinstance(text, str):
        return re.sub(pattern, '', text)
    # Jika bukan string/list
    return text

print("Removing harakat from Sanad...")

df['Sanad_no_harakat'] = df['Sanad'].apply(remove_harakat)

print("Harakat removal completed")
print("\n Sample result:\n")
print("Sanad asli:")
print(df['Sanad'].iloc[0])
print("\nSanad tanpa harakat:")
print(df['Sanad_no_harakat'].iloc[0])

Removing harakat from Sanad...
Harakat removal completed

 Sample result:

Sanad asli:
['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ', 'جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ', 'عَبْدِ اللَّهِ بْنِ عَبَّاسٍ']

Sanad tanpa harakat:
['أبو عبيدة مسلم بن أبي كريمة التميمي', 'جابر بن زيد الأزدي', 'عبد الله بن عباس']

In [52]:
df.head(3) #Mengecek apakah kolom Sanad_no_harakat sudah terbentuk

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length,Sanad_no_harakat
0,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ </NAR> , عَنْ <NAR> عَبْدِ اللَّهِ بْنِ عَبَّاسٍ </NAR> </SANAD> <MATN> ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" . </MATN>",مسند الربيع بن حبيب,1,"، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، قَالَ : "" نِيَّةُ الْمُؤْمِنِ خَيْرٌ مِنْ عَمَلِهِ "" .","[أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ, جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ, عَبْدِ اللَّهِ بْنِ عَبَّاسٍ]",3,"[أبو عبيدة مسلم بن أبي كريمة التميمي, جابر بن زيد الأزدي, عبد الله بن عباس]"
2,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> ، عَنْ <NAR> عَائِشَةَ </NAR> </SANAD> <MATN> ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي . </MATN>",مسند الربيع بن حبيب,3,"، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْهَا ، أَنَّهَا قَالَتْ : سَأَلَ الْحَارِثُ بْنُ هِشَامٍ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ : كَيْفَ يَأْتِيكَ الْوَحْيُ يَا رَسُولَ اللَّهِ ؟ ، قَالَ : "" أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ وَهُوَ أَشَدُّهُ عَلَيَّ فَيَفْصِمُ عَنِّي وَقَدْ وَعَيْتُ مَا قَالَ ، وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلا فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ "" ، قَالَتْ عَائِشَةُ ، رَضِيَ اللَّهُ عَنْهَا ، وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْيُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ وَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا ، قَالَ الرَّبِيعُ : فَيَفْصِمُ عَنْهُ أَيْ : فَيَنْجَلِي .","[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِشَةَ]",3,"[أبو عبيدة, جابر بن زيد, عائشة]"
3,"حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ <NAR> جَابِرِ بْنِ زَيْدٍ </NAR> </SANAD> <MATN> ، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" . </MATN>",مسند الربيع بن حبيب,4,"، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ ، أَنَّهُ قَالَ : "" عَلِّمُوا أَوْلادَكُمُ الْقُرْآنَ فَإِنَّهُ أَوَّلُ مَا يَنْبَغِي أَنْ يُتَعَلَّمَ مِنْ عِلْمِ اللَّهِ هُوَ "" .","[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]",2,"[أبو عبيدة, جابر بن زيد]"

### Mengecek Variasi Penulisan Nama Perawi 'عائشة' dan ابن عباس (untuk mencari dan menghitung semua variasi penulisan nama perawi dalam dataset sanad hadis)

In [53]:
# List nama perawi yang ingin dicari variasinya
nama_perawi = ['عائشة', 'ابن عباس']

for kata_cari in nama_perawi:
    # Pola regex huruf toleran harakat
    harakat_range = r'[\u064B-\u065F\u0670\u06D6-\u06ED]*'
    pattern = harakat_range.join(list(kata_cari))

    # Kumpulkan semua variasi ke satu list
    semua_variasi = []

    for row in df['Sanad_no_harakat']:
        try:
            sanad_list = ast.literal_eval(row) if isinstance(row, str) else row
        except:
            sanad_list = [row]

        for teks in sanad_list:
            matches = re.findall(pattern, teks)
            semua_variasi.extend(matches)

    # Hitung kemunculan setiap variasi
    counter = Counter(semua_variasi)

    # Ubah jadi DataFrame biar rapi
    df_hasil = pd.DataFrame(counter.items(), columns=['Variasi', 'Count']).sort_values(by='Count', ascending=False)

    print(f"Variasi untuk '{kata_cari}':")
    print(df_hasil)
    print("\n" + "="*50 + "\n")

Variasi untuk 'عائشة':
  Variasi  Count
0   عائشة  35170

==================================================

Variasi untuk 'ابن عباس':
    Variasi  Count
0  ابن عباس  49229

==================================================

### Normalisasi Alif dan Ya

In [54]:
def normalisasi_alif_ya(lst):
    if isinstance(lst, list):
        hasil = []
        for kata in lst:
           # 1. Seragamkan variasi alif jadi alif biasa
            kata = re.sub(r'[إأآ]', 'ا', kata)
            # 2. Seragamkan variasi ya jadi ي
            kata = re.sub(r'[ىېے]', 'ي', kata)

    
            hasil.append(kata)
        return hasil
    return lst

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(normalisasi_alif_ya)

print("Normalisasi alif dan ya selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Normalisasi alif dan ya selesai
Sample result:
0     [ابو عبيدة مسلم بن ابي كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
2                                                 [ابو عبيدة, جابر بن زيد, عائشة]
3                                                        [ابو عبيدة, جابر بن زيد]
4                                             [ابو عبيدة, جابر بن زيد, ابي هريرة]
5                                       [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
6                                              [ابو عبيدة, جابر بن زيد, ابن عباس]
7                                           [ابو عبيدة, جابر بن زيد, انس بن مالك]
8                                       [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
9                                             [ابو عبيدة, جابر بن زيد, ابي هريرة]
10                                        [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Validasi Sanad sebagai List dan Hitung Kemunculan Kata

In [55]:
#jika beberapa baris berformat string seperti "['a','b']"
def ensure_list(cell):
    if isinstance(cell, list):
        return cell
    if isinstance(cell, str) and cell.strip().startswith('['):
        try:
            return ast.literal_eval(cell)
        except Exception:
            return cell
    return cell

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(ensure_list)

#fungsi hitung (aman untuk list/str/NaN)
def count_occurrences(series, term):
    def cnt_cell(cell):
        if isinstance(cell, list):
            return sum(item.count(term) for item in cell if isinstance(item, str))
        elif isinstance(cell, str):
            return cell.count(term)
        else:
            return 0
    return int(series.apply(cnt_cell).sum())

kata_target = ['عائشة', 'ابن عباس']

for kata in kata_target:

    jumlah = count_occurrences(
        df['Sanad_no_harakat'],
        kata
    )

    print(f"Jumlah kemunculan '{kata}': {jumlah}")

Jumlah kemunculan 'عائشة': 35170
Jumlah kemunculan 'ابن عباس': 49229

### Membersihkan whitespace ekstra pada setiap elemen dalam daftar

In [56]:
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(lambda lst: [word.strip() for word in lst])

### Mengganti kata kekerabatan pada anggota keluarga

In [57]:
def ganti_kata_kekerabatan(lst):
    result = []
    prev_asli = None  # simpan nama tanpa harakat (karena semua tanpa harakat)

    for word in lst:
        word_no_harak = word

        if word_no_harak in [
            'ابيه','اباها','اباه','ابيهما','ابيا','ابيك','اباك',
            'ابان','ابوك','ابوه','ابانا','ابي','اب']:
            if prev_asli:
                result.append(f'ابو {prev_asli}')
            else:
                # prev_asli belum ada, jadi jangan diubah
                result.append(word)


        elif word_no_harak in ['جديه', 'جده', 'جدها']:
            if prev_asli:
                result.append(f'جد {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['ابائه', 'ابائهم']:
            if prev_asli:
                result.append(f'آباء {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['ابيها', 'أبيها', 'لأبيها']:
            if prev_asli:
                result.append(f'ابو {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['امه', 'أمه', 'امها', 'أمها']:
            if prev_asli:
                result.append(f'ام {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['جدته', 'جدتها']:
            if prev_asli:
                result.append(f'جدة {prev_asli}')
            else:
                result.append(word)

        else:
            result.append(word)
            prev_asli = word_no_harak

    return result


# Terapkan ke satu kolom
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(ganti_kata_kekerabatan)

print("Penggantian kata kekerabatan selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Penggantian kata kekerabatan selesai
Sample result:
0     [ابو عبيدة مسلم بن ابي كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
2                                                 [ابو عبيدة, جابر بن زيد, عائشة]
3                                                        [ابو عبيدة, جابر بن زيد]
4                                             [ابو عبيدة, جابر بن زيد, ابي هريرة]
5                                       [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
6                                              [ابو عبيدة, جابر بن زيد, ابن عباس]
7                                           [ابو عبيدة, جابر بن زيد, انس بن مالك]
8                                       [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
9                                             [ابو عبيدة, جابر بن زيد, ابي هريرة]
10                                        [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Menormalisasi nama perawi (Aba Abi Abu) menjadi Abu

In [58]:
def normalize_names(lst):
    normalized = []
    for word in lst:
        # ganti semua variasi ابا / ابي / ابو → ابو
        word = re.sub(r'\b(?:ابا|ابي|ابو)\b', 'ابو', word)
        normalized.append(word)
    return normalized

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(normalize_names)

print("Normalisasi kata 'abu' selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Normalisasi kata 'abu' selesai
Sample result:
0     [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
2                                                 [ابو عبيدة, جابر بن زيد, عائشة]
3                                                        [ابو عبيدة, جابر بن زيد]
4                                             [ابو عبيدة, جابر بن زيد, ابو هريرة]
5                                       [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
6                                              [ابو عبيدة, جابر بن زيد, ابن عباس]
7                                           [ابو عبيدة, جابر بن زيد, انس بن مالك]
8                                       [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
9                                             [ابو عبيدة, جابر بن زيد, ابو هريرة]
10                                        [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Membersihkan Elemen dan Filter Baris dengan 'ابو' dan Menghapus kata 'ابو'

In [59]:
# Memastikan semua elemen bersih
def clean_list(lst):
    return [x.strip() for x in lst]

# Terapkan ke DataFrame
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(clean_list)

# Ambil baris yang ada elemen exact 'ابو'
hasil_exact = df[df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]

print("Pembersihan dan filter selesai")
print(f"Jumlah baris yang mengandung 'ابو': {len(hasil_exact)}")
print("Sample hasil_exact:")
print(hasil_exact['Sanad_no_harakat'].head(5))

# Hapus baris yang ada elemen exact 'ابو'
df = df[~df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]

# Verifikasi penghapusan
baris_tersisa = df[df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]
print(f"Setelah penghapusan, jumlah baris yang masih mengandung 'ابو': {len(baris_tersisa)}")
if len(baris_tersisa) == 0:
    print("Penghapusan berhasil, tidak ada baris yang mengandung 'ابو' lagi.")
else:
    print("Masih ada baris yang mengandung 'ابو'.")

Pembersihan dan filter selesai
Jumlah baris yang mengandung 'ابو': 3233
Sample hasil_exact:
3008             [ابو, ابيه, علي بن ابو طالب]
3477               [ابو, ابيه, جده ، عن, علي]
15183                              [ابو, جدي]
15434    [ابو, طلحة, ام الدرداء, ابو الدرداء]
15443    [ابو, ورقبة بن مصقلة, نافع, ابن عمر]
Name: Sanad_no_harakat, dtype: object
Setelah penghapusan, jumlah baris yang masih mengandung 'ابو': 0
Penghapusan berhasil, tidak ada baris yang mengandung 'ابو' lagi.

### Filter Baris yang Dimulai dengan Kata Kekerabatan

In [60]:
target_words = [
    # أب variations 
    'ابيه','أبيه',
    'أباها','أباه',
    'ابيهما','أبيهما',
    'ابيا','أبيا',
    'ابيك','أبيك',
    'اباك','أباك',
    'ابان','أبان',
    'ابوك','أبوك',
    'ابوه','أبوه',
    'ابانا','أبانا',
    'ابي','ابيها','أبيها','لأبيها',
    'ابي', 'اب', 'اباه', 'اباها'

    # جد variations
    'جديه','جده','جدها','جدته','جدتها',

    # آباء variations
    'آبائه', 'ابائه', 'ابائهم'

    # أم variations
    'امه','أمه','امها','أمها'
]

def starts_with_target(lst):
    # pastikan bukan NaN dan berupa list
    if isinstance(lst, list) and len(lst) > 0:
        return lst[0] in target_words
    return False

# filter → ambil hanya yang BUKAN diawali target
df = df[~df['Sanad_no_harakat'].apply(starts_with_target)]

print("Filter selesai")
print(f"Jumlah baris setelah filter: {len(df)}")
print("Sample df setelah filter:")
print(df['Sanad_no_harakat'].head(5))

Filter selesai
Jumlah baris setelah filter: 487451
Sample df setelah filter:
0    [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
2                                                [ابو عبيدة, جابر بن زيد, عائشة]
3                                                       [ابو عبيدة, جابر بن زيد]
4                                            [ابو عبيدة, جابر بن زيد, ابو هريرة]
5                                      [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
Name: Sanad_no_harakat, dtype: object

In [61]:
def contains_exact_only(lst):
    target_words = [
    # أب variations
    'ابيه','أبيه',
    'أباها','أباه',
    'ابيهما','أبيهما',
    'ابيا','أبيا',
    'ابيك','أبيك',
    'اباك','أباك',
    'ابان','أبان',
    'ابوك','أبوك',
    'ابوه','أبوه',
    'ابانا','أبانا',
    'ابي','ابيها','أبيها','لأبيها',
    'ابي', 'اب', 'اباه', 'اباها'

    # جد variations
    'جديه','جده','جدها','جدته','جدتها',

    # آباء variations
    'آبائه', 'ابائه', 'ابائهم'

    # أم variations
    'امه','أمه','امها','أمها'
    ]# cek apakah list cuma berisi satu elemen dan sama dengan target
    return len(lst) == 1 and lst[0] in target_words

filtered_rows = df[df['Sanad_no_harakat'].apply(contains_exact_only)]

print("Filter selesai")
print(f"Jumlah baris yang hanya berisi satu kata kekerabatan: {len(filtered_rows)}")
print("Sample filtered_rows:")
print(filtered_rows['Sanad_no_harakat'].head(5))

filtered_rows

Filter selesai
Jumlah baris yang hanya berisi satu kata kekerabatan: 0
Sample filtered_rows:
Series([], Name: Sanad_no_harakat, dtype: object)

Empty DataFrame
Columns: [Hadith, Book, Num_hadith, Matn, Sanad, Sanad_Length, Sanad_no_harakat]
Index: []

In [62]:
transmission_words = {
    'حدثنا', 'حدثني', 'أخبرنا', 'أخبرني',
    'عن', 'قال', 'سمعت', 'روى'
}

remove_symbols_re = re.compile(r'[،:؛()\-/]')

def clean_list(lst):
    if not isinstance(lst, list):
        return lst

    result = []
    for x in lst:
        if not isinstance(x, str):
            continue

        text = x.strip()
        text = remove_symbols_re.sub('', text)

        if not text:
            continue

        if text in transmission_words:
            continue

        result.append(text)
    return result

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(clean_list)
print('Jumlah total baris di df:', len(df))

Jumlah total baris di df: 487451

In [63]:
# Daftar lafal periwayatan yang dihapus
lafal_periwayatan = [
    # Bentuk dasar
    'حدثنا', 'حدثني', 'حدث', 'حدثت',
    'اخبرنا', 'اخبرني', 'اخبر',
    'أخبرنا', 'أخبرني', 'أخبر',

    # Anba'
    'أنبأنا', 'انبانا',
    'أنبأني', 'انبأني',
    'انباني',

    # Qala dan turunannya
    'قال', 'قلت', 'يقول',
    'فقال', 'وقال', 'قالت',

    # Sami‘a
    'سمعت', 'يسمع',

    # Riwayat
    'روى', 'يروي',

    # Kata penghubung sanad
    'عن', 'ذكر',

    # Singkatan sanad
    'ثنا', 'نا',

    # Tambahan umum sanad
    'قرأت', 'قرأنا',
    'كتب', 'كتب إلي',
    'أملاء', 'إملاء',
    'سألت', 'سألنا',
    'حدثكم', 'حدثهم',
    'اخبركم', 'أخبركم',
    'أن', 'إن'
]

noise_patterns = [
    r'اهل الكوفة',
    r'اهل البصرة',
    r'اهل المدينة',
    r'اهل مكة',
    r'\bالي\b'
]

noise_words = [
    'IDF',
    'يعني'
]


# Gabungkan lafal menjadi regex
lafal_pattern = r'\b(?:' + '|'.join(map(re.escape, lafal_periwayatan)) + r')\b'
noise_pattern = '|'.join(noise_patterns)

# Karakter/simbol yang dihapus
pattern = r'[,،#()="{}\-\?\.:\|]+|<IDF>|</IDF>|\bIDF\b'

# Gabungkan regex
noise_words = '|'.join(noise_words)


# Fungsi cleaning
def clean_text(text):

    if not isinstance(text, str):
        return text

    # Hapus lafal periwayatan
    text = re.sub(lafal_pattern, ' ', text)

    # Hapus noise tambahan
    text = re.sub(noise_pattern, ' ', text)

    # Hapus noise
    text = re.sub(noise_pattern, ' ', text)

    # Hapus tag IDF
    text = re.sub(r'<\/?IDF>', ' ', text)

    # Hapus harakat Arab
    text = re.sub(r'[\u064B-\u065F\u0670]', '', text)

    # Hapus tanda baca Arab dan simbol
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text)
    
    # Hapus waw di awal kata
    text = re.sub(r'^و(?=[\u0600-\u06FF])', '', text)

    # Hapus tatweel
    text = re.sub(r'ـ+', '', text)

    # Hapus karakter/simbol khusus
    text = re.sub(pattern, '', text)

    # Hapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    # Hapus angka
    text = re.sub(r'\d+', '', text)

    # Hapus underscore
    text = text.replace('_', ' ')

    # hapus huruf ب di awal jika diikuti ابن
    text = re.sub(r'^ب(?=ابن)', '', text)

    return text

def ensure_list(cell):

    if isinstance(cell, list):
        return cell

    if isinstance(cell, str):

        # jika format string list
        if cell.strip().startswith('['):
            try:
                return ast.literal_eval(cell)
            except Exception:
                return [cell]

        return [cell]

    if pd.isna(cell):
        return []

    return [str(cell)]

# terapkan cleaning ke Sanad_no_harakat
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(ensure_list)

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(
    lambda sanad: [
        clean_text(x)
        for x in sanad
        if clean_text(x) != ''
    ]
)



# Tampilkan hasil
display(
    df[
        [
            'Sanad_no_harakat',
        ]
    ]
)

# Statistik jumlah sanad

print("Jumlah seluruh sanad :", len(df))

                                                                   Sanad_no_harakat
0       [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
2                                                   [ابو عبيدة, جابر بن زيد, عائشة]
3                                                          [ابو عبيدة, جابر بن زيد]
4                                               [ابو عبيدة, جابر بن زيد, ابو هريرة]
5                                         [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
...                                                                             ...
650981                                                             [ابو الخير, كعب]
650982                                                                    [ابن عمر]
650983                                                                   [ابن عباس]
650984                                                                   [ابن عباس]
650985                                                                   [ابو موسي]

[487451 rows x 1 columns]

Jumlah seluruh sanad : 487451

In [64]:
# Daftar lafaz periwayatan
hapus_kata = [
    "ثنا",
    "حدثنا",
    "قال حدثنا",
    "وقال",
    "عن",
    "أخبرنا",
    "أنبأنا",
    "حدثني",
    "حدثه",
    "سمعت",
    "يقول",
    "ذكر",
    "رواه",
    "حدث",
    "حكى"
]

hapus_kata = sorted(hapus_kata, key=len, reverse=True)
pola = r'\b(?:' + '|'.join(map(re.escape, hapus_kata)) + r')\b'


# Pastikan data berupa list
def ensure_list(cell):

    # Jika sudah list
    if isinstance(cell, list):
        return cell

    # Jika string
    if isinstance(cell, str):

        # Jika format string list
        if cell.strip().startswith('['):
            try:
                return ast.literal_eval(cell)
            except:
                return [cell]

        return [cell]

    # Jika NaN
    if pd.isna(cell):
        return []

    return [str(cell)]

# Terapkan ke kolom sanad
df['Sanad_no_harakat'] = (df['Sanad_no_harakat'].apply(ensure_list))

# Fungsi mencari lafaz yang ditemukan
def cari_lafaz(sanad):

    ditemukan = []

    for item in sanad:
        hasil = re.findall(
            pola,
            str(item)
        )
        if hasil:
            ditemukan.extend(hasil)

    # Hilangkan duplikat
    return list(set(ditemukan))


# Ambil data yang mengandung lafaz
mengandung_lafaz = df[
    df['Sanad_no_harakat'].apply(
        lambda sanad: any(
            re.search(pola, str(x))
            for x in sanad
        )
    )
].copy()


# Tambahkan kolom lafaz ditemukan
mengandung_lafaz['Lafaz_Ditemukan'] = (
    mengandung_lafaz['Sanad_no_harakat']
    .apply(cari_lafaz)
)

# Tampilkan sebelum cleaning
print("DATA YANG MENGANDUNG LAFAZ PERIWAYATAN")


display(mengandung_lafaz[['Sanad_no_harakat','Lafaz_Ditemukan']])

# Fungsi membersihkan sanad
def clean_sanad_list(sanad):

    hasil = []
    for item in sanad:
        # Hapus lafaz
        item = re.sub(
            pola,
            '',
            str(item)
        )
        # Rapikan spasi
        item = re.sub(
            r'\s+',
            ' ',
            item
        ).strip()
        # Jangan masukkan kosong
        if item != '':
            hasil.append(item)

    return hasil

# Simpan hasil cleaning
# Terapkan ke kolom Sanad_no_harakat
df['Sanad_no_harakat'] = (df['Sanad_no_harakat'].apply(clean_sanad_list))

df = df.reset_index(drop=True)

# Hitung jumlah sanad yang mengandung lafaz
jumlah_mengandung = len(mengandung_lafaz)

print("\nJumlah sanad yang mengandung lafaz:",
      jumlah_mengandung)

df[['Sanad_no_harakat']].head()

DATA YANG MENGANDUNG LAFAZ PERIWAYATAN

,Sanad_no_harakat,Lafaz_Ditemukan
282,"[ابو عبيدة, جابر بن زيد, ابو هريرة, عن ابو سعيد الخدري]",[عن]
7009,"[زيد بن اسلم, عطاء بن يسار, عن بسر بن سعيد, الاعرج, ابو هريرة]",[عن]
14069,"[ابو حنيفة, عمن حدثه, عطاء بن ابو رباح]",[حدثه]
14971,"[محمد بن عبد الرحمن بن ابو ليلي, عمن حدثه, عبد الله بن العباس, عمر بن الخطاب]",[حدثه]
14983,"[ابو حنيفة, عمن حدثه, عمر بن الخطاب]",[حدثه]
...,...,...
554498,"[اسرائيل, عبد العزيز بن رفيع, ابو صالح, عن علي بن ربيعة]",[عن]
568616,"[عبدة بن سليمان, سعيد بن ابو عروبة, عمن حدثه, يحيي بن ابو كثير, ابو الحسن]",[حدثه]
615254,"[عبد الرزاق, معمر, الزهري, سالم, ابن عمر, عن ايوب, نافع, ابن عمر]",[عن]
615815,"[يزيد, يزيد, الحجاج, الحجاج بن ارطاة, عطاء, ابراهيم بن عامر, عن عمرو بن شعيب, سعيد بن المسيب, عن الزهري, ابو وعن الزهري, جد وعن الزهري, حميد بن عبد الرحمن, ابو هريرة]",[عن]
634522,"[ابو الفتح يوسف بن عبد الواحد, شجاع بن علي, ابو عبد الله بن سندة, احمد بن محمد بن زياد, محمد بن يعقوب, احمد بن عبد الحميد الحارثي, معاوية بن هشام, سفيان الثوري, منصور, مجاهد, عطاء, ايمن الحبشي ان النبي صلي الله عليه وسلم قطع اليد في مجن وقيمته يومئذ دينار رواه غيرهما عكرمة مجاهد وعن عطاء, ابو الحسين بن الابنوسي, عيسي بن علي, عبد الله بن محمد, عمي, محمد بن سعيد بن الاصبهاني, معاوية بن هشام, سفيان, منصور, مجاهد, عطاء, ايمن L]",[رواه]

Jumlah sanad yang mengandung lafaz: 185

                                                              Sanad_no_harakat
0  [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
1                                              [ابو عبيدة, جابر بن زيد, عائشة]
2                                                     [ابو عبيدة, جابر بن زيد]
3                                          [ابو عبيدة, جابر بن زيد, ابو هريرة]
4                                    [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]

In [65]:
# Cek karakter selain huruf Arab
def check_non_arabic(text):

    if not isinstance(text, str):
        return False

    # Cari karakter selain Arab dan spasi
    return bool(
        re.search(r'[^\u0600-\u06FF\s]', text)
    )

# Ambil data yang masih memiliki
# karakter non-Arab pada kolom Guru atau Murid
non_arabic_df = df[
    df['Sanad_no_harakat'].apply(check_non_arabic)
]

# Tampilkan hasil
display(non_arabic_df[['Sanad_no_harakat']].head(20))

# Jumlah data
print("Jumlah data dengan karakter non-Arab:")
print(len(non_arabic_df))

Empty DataFrame
Columns: [Sanad_no_harakat]
Index: []

Jumlah data dengan karakter non-Arab:
0

In [66]:
df.shape

(487451, 7)

### Print Cleaned data

In [67]:
df[df['Sanad_no_harakat'].apply(
    lambda sanad: any(re.search(pola, str(x)) for x in sanad)
)]

Empty DataFrame
Columns: [Hadith, Book, Num_hadith, Matn, Sanad, Sanad_Length, Sanad_no_harakat]
Index: []

### Menampilkan Kolom Sanad dan Sanad_no_harakat

In [68]:
# Menampilkan kedua kolom Sanad dan Sanad_no_harakat
df_display = df[['Sanad', 'Sanad_no_harakat']].copy()
pd.set_option('display.max_colwidth', None)
print("Kolom Sanad dan Sanad_no_harakat:")
print(df_display.head(10))

Kolom Sanad dan Sanad_no_harakat:
                                                                                                                           Sanad  \
0  [أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ, جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ, عَبْدِ اللَّهِ بْنِ عَبَّاسٍ]
1                                                                             [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِشَةَ]
2                                                                                        [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]
3                                                                      [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي هُرَيْرَةَ]
4                                                            [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي سَعِيدٍ الْخُدْرِيِّ]
5                                                                        [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, ابْنِ عَبَّاسٍ]
6                                                                   [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَنَسِ بْنِ مَالِكٍ]
7                                                            [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي سَعِيدٍ الْخُدْرِيِّ]
8                                                                      [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي هُرَيْرَةَ]
9                                                               [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, عُمَرَ بْنَ الْخَطَّابِ]

                                                              Sanad_no_harakat
0  [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]
1                                              [ابو عبيدة, جابر بن زيد, عائشة]
2                                                     [ابو عبيدة, جابر بن زيد]
3                                          [ابو عبيدة, جابر بن زيد, ابو هريرة]
4                                    [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
5                                           [ابو عبيدة, جابر بن زيد, ابن عباس]
6                                        [ابو عبيدة, جابر بن زيد, انس بن مالك]
7                                    [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
8                                          [ابو عبيدة, جابر بن زيد, ابو هريرة]
9                                      [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]

In [69]:
# Tampilkan semua baris dari kedua kolom
print(f"\nTotal baris: {len(df)}")
print("\nSanad (Original) dan Sanad_no_harakat (Cleaned):")
df_display

Total baris: 487451

Sanad (Original) dan Sanad_no_harakat (Cleaned):

,Sanad,Sanad_no_harakat
0,"[أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ, جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ, عَبْدِ اللَّهِ بْنِ عَبَّاسٍ]","[ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن زيد الازدي, عبد الله بن عباس]"
1,"[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِشَةَ]","[ابو عبيدة, جابر بن زيد, عائشة]"
2,"[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]","[ابو عبيدة, جابر بن زيد]"
3,"[أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي هُرَيْرَةَ]","[ابو عبيدة, جابر بن زيد, ابو هريرة]"
4,"[أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي سَعِيدٍ الْخُدْرِيِّ]","[ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]"
...,...,...
487446,"[أبي الخير, كعب]","[ابو الخير, كعب]"
487447,[ابن عمر],[ابن عمر]
487448,[بِابْنِ عَبَّاسٍ],[ابن عباس]
487449,[ابْنِ عَبَّاسٍ],[ابن عباس]
487450,[أَبُو مُوسَى],[ابو موسي]

In [71]:
df.to_csv('../data/processed/sanadset_cleaned.csv', index=False, encoding='utf-8-sig')