# Load data Sanadset

## Import Library

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import ast
import re
from collections import Counter

## Load Data

In [3]:
# pd.set_option('display.max_colwidth', None)

df = pd.read_csv('../data/raw/sanadset.csv', header=None)
df.columns = ['Hadith', 'Book', 'Num_hadith', 'Matn', 'Sanad', 'Sanad_Length']
df = df.iloc[1:].reset_index(drop=True)

# Pastikan kolom Sanad ada
assert 'Sanad' in df.columns, "❌ Kolom 'Sanad' tidak ditemukan!"

print(f" Data loaded: {len(df)} baris")
print(f" Kolom: {df.columns.tolist()}")
print(f" Tipe data: {df.dtypes.to_dict()}")

print(f"\n Sample data:")
print(df.head(3))

df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_31960\1846584940.py:3: DtypeWarning: Columns (0: 2, 1: 5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/sanadset.csv', header=None)

 Data loaded: 650986 baris
 Kolom: ['Hadith', 'Book', 'Num_hadith', 'Matn', 'Sanad', 'Sanad_Length']
 Tipe data: {'Hadith': <StringDtype(storage='python', na_value=nan)>, 'Book': <StringDtype(storage='python', na_value=nan)>, 'Num_hadith': dtype('O'), 'Matn': <StringDtype(storage='python', na_value=nan)>, 'Sanad': <StringDtype(storage='python', na_value=nan)>, 'Sanad_Length': dtype('O')}

 Sample data:
                                              Hadith                 Book  \
0  حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْ...  مسند الربيع بن حبيب
1  <MATN> وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْر...  مسند الربيع بن حبيب
2  حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...  مسند الربيع بن حبيب

  Num_hadith                                               Matn  \
0          1    ، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَ...
1          2  وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْ...
2          3    ، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْ...

                                               Sanad Sanad_Length
0  ['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَ...            3
1                                           No SANAD            0
2  ['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'ع...            3

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length
0,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْ...,مسند الربيع بن حبيب,1,، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَ...,['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَ...,3
1,<MATN> وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْر...,مسند الربيع بن حبيب,2,وَبِهَذَا السَّنَدِ فِي رِوَايَةٍ أُخْرَى عَنْ...,No SANAD,0
2,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,3,، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْ...,"['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'ع...",3
3,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,4,، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَل...,"['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ']",2
4,<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ ...,مسند الربيع بن حبيب,5,، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْ...,"['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أ...",3
...,...,...,...,...,...,...
650981,وعن وعن <SANAD> <NAR> أبي الخير </NAR> ، قال ...,إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6205,""" نهر النيل نهر العسل في الجنة ، ونهر دجلة ن...","['أبي الخير', 'كعب']",2
650982,وعن <SANAD> <NAR> ابن عمر </NAR> </SANAD> <MAT...,إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6206,"، رَضِيَ اللَّهُ عنهما ، قال : "" ألا أخبركم ...",['ابن عمر'],1
650983,"- وَعَنْ - وَعَنْ مُجَاهِدٍ ، قَالَ : "" مَرَّ ...",إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6207,، فَقَالَ : إِنَّ هَذَا الرَّجُلَ يُحِبُّنِي...,['بِابْنِ عَبَّاسٍ'],1
650984,- وَعَنْ - وَعَنْ أَبِي ظَبْيَانَ ، عَنِ <SANA...,إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6208,", رَضِيَ اللَّهُ عَنْهُمَا , "" لَيْسَ فِي ال...",['ابْنِ عَبَّاسٍ'],1
650985,- وَعَنْ - وَعَنْ أَسْلَمَ ، عَنِ امْرَأَتِهِ ...,إتحاف الخيرة المهرة بزوائد المسانيد العشرة,6209,رَضِيَ اللَّهُ عَنْهُ ، فَبَيْنَا نَحْنُ كَذ...,['أَبُو مُوسَى'],1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 650986 entries, 0 to 650985
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Hadith        650986 non-null  str
 1   Book          650986 non-null  str
 2   Num_hadith    650986 non-null  object
 3   Matn          650986 non-null  str
 4   Sanad         650986 non-null  str
 5   Sanad_Length  650986 non-null  object
dtypes: object(2), str(4)
memory usage: 29.8+ MB

# Pembersihan Data Sanadset

### Menghapus No Sanad di Kolom Sanad

In [5]:
# Hapus baris 'No SANAD'
df = df[df['Sanad'] != 'No SANAD'].copy()

# Print jumlah data setelah filtering
print("Jumlah data setelah No SANAD dihapus:", len(df))
df.head(5)

Jumlah data setelah No SANAD dihapus: 491428

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length
0,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْ...,مسند الربيع بن حبيب,1,، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَ...,['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَ...,3
2,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,3,، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْ...,"['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ', 'ع...",3
3,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,4,، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَل...,"['أَبُو عُبَيْدَةَ', 'جَابِرِ بْنِ زَيْدٍ']",2
4,<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ ...,مسند الربيع بن حبيب,5,، عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْ...,"['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أ...",3
5,<SANAD> <NAR> أَبُو عُبَيْدَةَ </NAR> ، عَنْ ...,مسند الربيع بن حبيب,6,، قَالَ : قَالَ رَسُولُ اللَّهِ صَلَّى اللَّ...,"['أَبُو عُبَيْدَةَ', 'جَابِرُ بْنُ زَيْدٍ', 'أ...",3

### Ubah Sanad dari String ke List

In [6]:
# Ubah nilai string yang merepresentasikan list menjadi object list Python

def parse_list(value):
    if isinstance(value, str):
        try:
            return ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return value
    return value

df['Sanad'] = df['Sanad'].apply(parse_list)

print(df['Sanad'].head())
print(type(df['Sanad'].iloc[0]))

0    [أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَة...
2    [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِش...
3              [أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]
4    [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي ...
5    [أَبُو عُبَيْدَةَ, جَابِرُ بْنُ زَيْدٍ, أَبِي ...
Name: Sanad, dtype: object
<class 'list'>

### Menghilangkan Harakat

In [7]:
def remove_harakat(text): ## Remove Arabic diacritics (harakat)

    # Regex karakter harakat Arab
    pattern = r'[\u064B-\u065F\u0670\u06D6-\u06ED]'
    # Jika data berupa list
    if isinstance(text, list):
        return [
            re.sub(pattern, '', str(t))
            for t in text]
    # Jika data berupa string
    elif isinstance(text, str):
        return re.sub(pattern, '', text)
    # Jika bukan string/list
    return text

print("Removing harakat from Sanad...")

df['Sanad_no_harakat'] = df['Sanad'].apply(remove_harakat)

print("Harakat removal completed")
print("\n Sample result:\n")
print("Sanad asli:")
print(df['Sanad'].iloc[0])
print("\nSanad tanpa harakat:")
print(df['Sanad_no_harakat'].iloc[0])

Removing harakat from Sanad...
Harakat removal completed

 Sample result:

Sanad asli:
['أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَةَ التَّمِيمِيُّ', 'جَابِرِ بْنِ زَيْدٍ الأَزْدِيِّ', 'عَبْدِ اللَّهِ بْنِ عَبَّاسٍ']

Sanad tanpa harakat:
['أبو عبيدة مسلم بن أبي كريمة التميمي', 'جابر بن زيد الأزدي', 'عبد الله بن عباس']

In [8]:
df.head(3) #Mengecek apakah kolom Sanad_no_harakat sudah terbentuk

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length,Sanad_no_harakat
0,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ مُسْ...,مسند الربيع بن حبيب,1,، عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَ...,[أَبُو عُبَيْدَةَ مُسْلِمُ بْنُ أَبِي كَرِيمَة...,3,"[أبو عبيدة مسلم بن أبي كريمة التميمي, جابر بن ..."
2,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,3,، أُمِّ الْمُؤْمِنِينَ ، رَضِيَ اللَّهُ عَنْ...,"[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ, عَائِش...",3,"[أبو عبيدة, جابر بن زيد, عائشة]"
3,حَدَّثَنِي <SANAD> <NAR> أَبُو عُبَيْدَةَ </NA...,مسند الربيع بن حبيب,4,، قَالَ : بَلَغَنِي عَنْ رَسُولِ اللَّهِ صَل...,"[أَبُو عُبَيْدَةَ, جَابِرِ بْنِ زَيْدٍ]",2,"[أبو عبيدة, جابر بن زيد]"

### Mengecek Variasi Penulisan Nama Perawi 'عائشة' dan ابن عباس (untuk mencari dan menghitung semua variasi penulisan nama perawi dalam dataset sanad hadis)

In [9]:
# List nama perawi yang ingin dicari variasinya
nama_perawi = ['عائشة', 'ابن عباس']

for kata_cari in nama_perawi:
    # Pola regex huruf toleran harakat
    harakat_range = r'[\u064B-\u065F\u0670\u06D6-\u06ED]*'
    pattern = harakat_range.join(list(kata_cari))

    # Kumpulkan semua variasi ke satu list
    semua_variasi = []

    for row in df['Sanad_no_harakat']:
        try:
            sanad_list = ast.literal_eval(row) if isinstance(row, str) else row
        except:
            sanad_list = [row]

        for teks in sanad_list:
            matches = re.findall(pattern, teks)
            semua_variasi.extend(matches)

    # Hitung kemunculan setiap variasi
    counter = Counter(semua_variasi)

    # Ubah jadi DataFrame biar rapi
    df_hasil = pd.DataFrame(counter.items(), columns=['Variasi', 'Count']).sort_values(by='Count', ascending=False)

    print(f"Variasi untuk '{kata_cari}':")
    print(df_hasil)
    print("\n" + "="*50 + "\n")

Variasi untuk 'عائشة':
  Variasi  Count
0   عائشة  35170

==================================================

Variasi untuk 'ابن عباس':
    Variasi  Count
0  ابن عباس  49229

==================================================

### Normalisasi Alif dan Ya

In [10]:
def normalisasi_alif_ya(lst):
    if isinstance(lst, list):
        hasil = []
        for kata in lst:
            # 1. Seragamkan variasi alif jadi alif biasa
            kata = re.sub(r'[إأآ]', 'ا', kata)
            # 2. Seragamkan variasi ya jadi ي
            kata = re.sub(r'[ىېے]', 'ي', kata)
            hasil.append(kata)
        return hasil
    return lst

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(normalisasi_alif_ya)

print("Normalisasi alif dan ya selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Normalisasi alif dan ya selesai
Sample result:
0     [ابو عبيدة مسلم بن ابي كريمة التميمي, جابر بن ...
2                       [ابو عبيدة, جابر بن زيد, عائشة]
3                              [ابو عبيدة, جابر بن زيد]
4                   [ابو عبيدة, جابر بن زيد, ابي هريرة]
5             [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
6                    [ابو عبيدة, جابر بن زيد, ابن عباس]
7                 [ابو عبيدة, جابر بن زيد, انس بن مالك]
8             [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
9                   [ابو عبيدة, جابر بن زيد, ابي هريرة]
10              [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Validasi Sanad sebagai List dan Hitung Kemunculan Kata

In [11]:
#jika beberapa baris berformat string seperti "['a','b']"
def ensure_list(cell):
    if isinstance(cell, list):
        return cell
    if isinstance(cell, str) and cell.strip().startswith('['):
        try:
            return ast.literal_eval(cell)
        except Exception:
            return cell
    return cell

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(ensure_list)

#fungsi hitung (aman untuk list/str/NaN)
def count_occurrences(series, term):
    def cnt_cell(cell):
        if isinstance(cell, list):
            return sum(item.count(term) for item in cell if isinstance(item, str))
        elif isinstance(cell, str):
            return cell.count(term)
        else:
            return 0
    return int(series.apply(cnt_cell).sum())

kata_target = ['عائشة', 'ابن عباس']

for kata in kata_target:

    jumlah = count_occurrences(
        df['Sanad_no_harakat'],
        kata
    )

    print(f"Jumlah kemunculan '{kata}': {jumlah}")

Jumlah kemunculan 'عائشة': 35170
Jumlah kemunculan 'ابن عباس': 49229

### Membersihkan whitespace ekstra pada setiap elemen dalam daftar

In [12]:
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(lambda lst: [word.strip() for word in lst])

### Mengganti kata kekerabatan pada anggota keluarga

In [13]:
def ganti_kata_kekerabatan(lst):
    result = []
    prev_asli = None  # simpan nama tanpa harakat (karena semua tanpa harakat)

    for word in lst:
        word_no_harak = word

        if word_no_harak in [
            'ابيه','اباها','اباه','ابيهما','ابيا','ابيك','اباك',
            'ابان','ابوك','ابوه','ابانا','ابي','اب']:
            if prev_asli:
                result.append(f'ابو {prev_asli}')
            else:
                # prev_asli belum ada, jadi jangan diubah
                result.append(word)


        elif word_no_harak in ['جديه', 'جده', 'جدها']:
            if prev_asli:
                result.append(f'جد {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['ابائه', 'ابائهم']:
            if prev_asli:
                result.append(f'آباء {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['ابيها', 'أبيها', 'لأبيها']:
            if prev_asli:
                result.append(f'ابو {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['امه', 'أمه', 'امها', 'أمها']:
            if prev_asli:
                result.append(f'ام {prev_asli}')
            else:
                result.append(word)

        elif word_no_harak in ['جدته', 'جدتها']:
            if prev_asli:
                result.append(f'جدة {prev_asli}')
            else:
                result.append(word)

        else:
            result.append(word)
            prev_asli = word_no_harak

    return result


# Terapkan ke satu kolom
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(ganti_kata_kekerabatan)

print("Penggantian kata kekerabatan selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Penggantian kata kekerabatan selesai
Sample result:
0     [ابو عبيدة مسلم بن ابي كريمة التميمي, جابر بن ...
2                       [ابو عبيدة, جابر بن زيد, عائشة]
3                              [ابو عبيدة, جابر بن زيد]
4                   [ابو عبيدة, جابر بن زيد, ابي هريرة]
5             [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
6                    [ابو عبيدة, جابر بن زيد, ابن عباس]
7                 [ابو عبيدة, جابر بن زيد, انس بن مالك]
8             [ابو عبيدة, جابر بن زيد, ابي سعيد الخدري]
9                   [ابو عبيدة, جابر بن زيد, ابي هريرة]
10              [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Menormalisasi nama perawi (Aba Abi Abu) menjadi Abu

In [14]:
def normalize_names(lst):
    normalized = []
    for word in lst:
        # ganti semua variasi ابا / ابي / ابو → ابو
        word = re.sub(r'\b(?:ابا|ابي|ابو)\b', 'ابو', word)
        normalized.append(word)
    return normalized

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(normalize_names)

print("Normalisasi kata 'abu' selesai")
print("Sample result:")
print(df['Sanad_no_harakat'].head(10))

Normalisasi kata 'abu' selesai
Sample result:
0     [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن ...
2                       [ابو عبيدة, جابر بن زيد, عائشة]
3                              [ابو عبيدة, جابر بن زيد]
4                   [ابو عبيدة, جابر بن زيد, ابو هريرة]
5             [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
6                    [ابو عبيدة, جابر بن زيد, ابن عباس]
7                 [ابو عبيدة, جابر بن زيد, انس بن مالك]
8             [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
9                   [ابو عبيدة, جابر بن زيد, ابو هريرة]
10              [ابو عبيدة, جابر بن زيد, عمر بن الخطاب]
Name: Sanad_no_harakat, dtype: object

### Membersihkan Elemen dan Filter Baris dengan 'ابو' dan Menghapus kata 'ابو'

In [15]:
# Memastikan semua elemen bersih
def clean_list(lst):
    return [x.strip() for x in lst]

# Terapkan ke DataFrame
df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(clean_list)

# Ambil baris yang ada elemen exact 'ابو'
hasil_exact = df[df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]

print("Pembersihan dan filter selesai")
print(f"Jumlah baris yang mengandung 'ابو': {len(hasil_exact)}")
print("Sample hasil_exact:")
print(hasil_exact['Sanad_no_harakat'].head(5))

# Hapus baris yang ada elemen exact 'ابو'
df = df[~df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]

# Verifikasi penghapusan
baris_tersisa = df[df['Sanad_no_harakat'].apply(lambda lst: 'ابو' in lst)]
print(f"Setelah penghapusan, jumlah baris yang masih mengandung 'ابو': {len(baris_tersisa)}")
if len(baris_tersisa) == 0:
    print("Penghapusan berhasil, tidak ada baris yang mengandung 'ابو' lagi.")
else:
    print("Masih ada baris yang mengandung 'ابو'.")

Pembersihan dan filter selesai
Jumlah baris yang mengandung 'ابو': 3233
Sample hasil_exact:
3008             [ابو, ابيه, علي بن ابو طالب]
3477               [ابو, ابيه, جده ، عن, علي]
15183                              [ابو, جدي]
15434    [ابو, طلحة, ام الدرداء, ابو الدرداء]
15443    [ابو, ورقبة بن مصقلة, نافع, ابن عمر]
Name: Sanad_no_harakat, dtype: object
Setelah penghapusan, jumlah baris yang masih mengandung 'ابو': 0
Penghapusan berhasil, tidak ada baris yang mengandung 'ابو' lagi.

### Filter Baris yang Dimulai dengan Kata Kekerabatan

In [16]:
target_words = [
    # أب variations 
    'ابيه','أبيه',
    'أباها','أباه',
    'ابيهما','أبيهما',
    'ابيا','أبيا',
    'ابيك','أبيك',
    'اباك','أباك',
    'ابان','أبان',
    'ابوك','أبوك',
    'ابوه','أبوه',
    'ابانا','أبانا',
    'ابي','ابيها','أبيها','لأبيها',
    'ابي', 'اب', 'اباه', 'اباها'

    # جد variations
    'جديه','جده','جدها','جدته','جدتها',

    # آباء variations
    'آبائه', 'ابائه', 'ابائهم'

    # أم variations
    'امه','أمه','امها','أمها'
]

def starts_with_target(lst):
    # pastikan bukan NaN dan berupa list
    if isinstance(lst, list) and len(lst) > 0:
        return lst[0] in target_words
    return False

# filter → ambil hanya yang BUKAN diawali target
df = df[~df['Sanad_no_harakat'].apply(starts_with_target)]

print("Filter selesai")
print(f"Jumlah baris setelah filter: {len(df)}")
print("Sample df setelah filter:")
print(df['Sanad_no_harakat'].head(5))

Filter selesai
Jumlah baris setelah filter: 487451
Sample df setelah filter:
0    [ابو عبيدة مسلم بن ابو كريمة التميمي, جابر بن ...
2                      [ابو عبيدة, جابر بن زيد, عائشة]
3                             [ابو عبيدة, جابر بن زيد]
4                  [ابو عبيدة, جابر بن زيد, ابو هريرة]
5            [ابو عبيدة, جابر بن زيد, ابو سعيد الخدري]
Name: Sanad_no_harakat, dtype: object

In [ ]:
def contains_exact_only(lst):
    target_words = [
    # أب variations
    'ابيه','أبيه',
    'أباها','أباه',
    'ابيهما','أبيهما',
    'ابيا','أبيا',
    'ابيك','أبيك',
    'اباك','أباك',
    'ابان','أبان',
    'ابوك','أبوك',
    'ابوه','أبوه',
    'ابانا','أبانا',
    'ابي','ابيها','أبيها','لأبيها',
    'ابي', 'اب', 'اباه', 'اباها'

    # جد variations
    'جديه','جده','جدها','جدته','جدتها',

    # آباء variations
    'آبائه', 'ابائه', 'ابائهم'

    # أم variations
    'امه','أمه','امها','أمها'
    ]# cek apakah list cuma berisi satu elemen dan sama dengan target
    return len(lst) == 1 and lst[0] in target_words

filtered_rows = hasil1[hasil1['Sanad_no_harakat'].apply(contains_exact_only)]

print("Filter selesai")
print(f"Jumlah baris yang hanya berisi satu kata kekerabatan: {len(filtered_rows)}")
print("Sample filtered_rows:")
print(filtered_rows['Sanad_no_harakat'].head(5))

filtered_rows

Filter selesai
Jumlah baris yang hanya berisi satu kata kekerabatan: 408
Sample filtered_rows:
4744      [ابان]
5564     [ابيها]
5931      [ابان]
16915      [جده]
23005      [ابي]
Name: Sanad_no_harakat, dtype: object

,Hadith,Book,Num_hadith,Matn,Sanad,Sanad_Length,Sanad_no_harakat
4744,عَنْ <SANAD> <NAR> أَبَانَ </NAR> </SANAD> <MA...,الجامع لمعمر بن راشد,384,، أَنّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَ...,[أَبَانَ],1,[ابان]
5564,عَنْ عَنْ عَبْدِ الْكَرِيمِ الْجَزَرِيِّ ، عَن...,الجامع لمعمر بن راشد,1205,"تَشْكُو الزُّبَيْرَ ، فَقَالَ : "" ارْجِعِي ي...",[أَبِيهَا],1,[ابيها]
5931,عَنْ <SANAD> <NAR> أَبَانَ </NAR> </SANAD> <MA...,الجامع لمعمر بن راشد,1572,، أَنّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَ...,[أَبَانَ],1,[ابان]
16915,حَدَّثَنَا حَدَّثَنَا زُهَيْرُ بْنُ مُعَاوِيَة...,الخراج ليحيى بن آدم,296,، أَنَّ غُلامًا لَهُمْ بَاعَ لَهُمْ فَضْلَ م...,[جَدِّهِ],1,[جده]
23005,حَدَّثَنَا حَدَّثَنَا عَبْدُ الْوَاحِدِ بْنُ س...,مسند أبي داود الطيالسي,573,، فَقَالَ : يَا بُنَيَّ ، اتَّقِ اللَّهَ وَا...,[أَبِي],1,[ابي]
...,...,...,...,...,...,...,...
604706,قَالَ : فَإِذَا كَانَ بِالْغَدَاةِ ، فَاغْدُ ع...,مسند أحمد بن حنبل,20637,عَلَيْهِمَا وَقَدْ تَوَضَّأَ ، فَقَالَ : إِن...,[أُبَيٌّ],1,[ابي]
627501,وَبِإِسْنَادِهِ ، وَبِإِسْنَادِهِ ، عَنْ <SANA...,شعب الإيمان للبيهقي,6233,"، قَالَ : "" مَرَّ رَسُولُ اللَّهِ صَلَّى الل...",[أَبِيهِ],1,[ابيه]
630192,أَخْبَرَنَا أَبُو الْحَسَنِ الْمُقْرِي ، قَالَ...,شعب الإيمان للبيهقي,8932,، عَنْ سَعْدٍ ، عَنِ النَّبِيِّ ، صَلَّى اللّ...,[أَبِيهِ],1,[ابيه]
642951,أَخْبَرَنَا أَخْبَرَنَا أَبُو غَالِبٍ أَحْمَدُ...,تاريخ دمشق لابن عساكر,11255,، قَالَ : أَعَانَ جِبْرِيلُ عَلَيْهِ السَّلا...,[أَبِيهِ],1,[ابيه]
647522,وَقَالَ وَقَالَ مُسَدَّدٌ : ثنا أَبُو مُعَاوِي...,إتحاف الخيرة المهرة بزوائد المسانيد العشرة,2727,"، قَالَ : "" كَتَبَ عُمَرُو بْنُ الْعَاصِ إِل...",[جَدِّهِ],1,[جده]

### hapus

In [19]:
transmission_words = {
    'حدثنا', 'حدثني', 'أخبرنا', 'أخبرني',
    'عن', 'قال', 'سمعت', 'روى'
}

remove_symbols_re = re.compile(r'[،:؛()\-/]')

def clean_list(lst):
    if not isinstance(lst, list):
        return lst

    result = []
    for x in lst:
        if not isinstance(x, str):
            continue

        text = x.strip()
        text = remove_symbols_re.sub('', text)

        if not text:
            continue

        if text in transmission_words:
            continue

        result.append(text)
    return result

df['Sanad_no_harakat'] = df['Sanad_no_harakat'].apply(clean_list)
print('Jumlah total baris di df:', len(df))

Jumlah total baris di df: 487451

### Print Cleaned data

In [20]:
df.to_csv('../data/processed/sanadset_cleaned.csv', index=False, encoding='utf-8-sig')